//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CliCountry.Facturacion.Negocio.Comun.Recursos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ReglasNegocio {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReglasNegocio() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CliCountry.Facturacion.Negocio.Comun.Recursos.ReglasNegocio", typeof(ReglasNegocio).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al almacenar el criterio de aproximación..
        /// </summary>
        internal static string Aproximacion_ErrorGuardarCriterio {
            get {
                return ResourceManager.GetString("Aproximacion_ErrorGuardarCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al almacenar los límites de intervalos..
        /// </summary>
        internal static string Aproximacion_ErrorGuardarIntervalo {
            get {
                return ResourceManager.GetString("Aproximacion_ErrorGuardarIntervalo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se presentó un error al actualizar el criterio de aproximación.
        /// </summary>
        internal static string Aproximaciones_MsjErrActualizar {
            get {
                return ResourceManager.GetString("Aproximaciones_MsjErrActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se presentó un error al crear el criterio de aproximación.
        /// </summary>
        internal static string Aproximaciones_MsjErrCrear {
            get {
                return ResourceManager.GetString("Aproximaciones_MsjErrCrear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se presentó un error al eliminar los límites..
        /// </summary>
        internal static string Aproximaciones_MsjErrEliminarInt {
            get {
                return ResourceManager.GetString("Aproximaciones_MsjErrEliminarInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se presentó un error al guardar los límites..
        /// </summary>
        internal static string Aproximaciones_MsjErrGuardarInt {
            get {
                return ResourceManager.GetString("Aproximaciones_MsjErrGuardarInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo de convenio no clínico debe ser instanciado con el IdManual.
        /// </summary>
        internal static string ConvenioNoClinico_NoInstanciado {
            get {
                return ResourceManager.GetString("ConvenioNoClinico_NoInstanciado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El producto no tiene una tarifa definida IdProducto:{0} Nombre:{1} Atención:{2}.
        /// </summary>
        internal static string DetalleTarifa_AjusteTarifa {
            get {
                return ResourceManager.GetString("DetalleTarifa_AjusteTarifa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encuentra configurado el valor para el  IdProducto:{0} Nombre:{1} Atención:{2}, relacionado al ajuste de tarifa.
        /// </summary>
        internal static string DetalleTarifa_Porcentaje {
            get {
                return ResourceManager.GetString("DetalleTarifa_Porcentaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregado.
        /// </summary>
        internal static string EstadoAgregado {
            get {
                return ResourceManager.GetString("EstadoAgregado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrado.
        /// </summary>
        internal static string EstadoBorrado {
            get {
                return ResourceManager.GetString("EstadoBorrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo de grupo de producto debe tener un valor o ser instanciado con el constructor por defecto.
        /// </summary>
        internal static string GrupoProducto_NoInstanciado {
            get {
                return ResourceManager.GetString("GrupoProducto_NoInstanciado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encuentra configurado la homologación para el producto {0} Atención:{1}.
        /// </summary>
        internal static string HomologacionProducto_SinDato {
            get {
                return ResourceManager.GetString("HomologacionProducto_SinDato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se presentó un error al crear el detalle del nivel de complejidad..
        /// </summary>
        internal static string NivelComplejidad_ErrorCrearDetalle {
            get {
                return ResourceManager.GetString("NivelComplejidad_ErrorCrearDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se presentó un error al crear el nivel de complejidad.
        /// </summary>
        internal static string NivelComplejidad_ErrorCrearNivel {
            get {
                return ResourceManager.GetString("NivelComplejidad_ErrorCrearNivel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El producto {0} - {1} No tiene nivel de complejidad configurado.
        /// </summary>
        internal static string NivelComplejidad_Nivel {
            get {
                return ResourceManager.GetString("NivelComplejidad_Nivel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insertar.
        /// </summary>
        internal static string OperacionInsertar {
            get {
                return ResourceManager.GetString("OperacionInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar.
        /// </summary>
        internal static string OperacionModificar {
            get {
                return ResourceManager.GetString("OperacionModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo de producto debe tener un valor o ser instanciado con el constructor por defecto.
        /// </summary>
        internal static string Producto_NoInstanciado {
            get {
                return ResourceManager.GetString("Producto_NoInstanciado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.
        /// </summary>
        internal static string Tarifas_TipoFacturacion {
            get {
                return ResourceManager.GetString("Tarifas_TipoFacturacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T.
        /// </summary>
        internal static string Tarifas_TipoTarifas {
            get {
                return ResourceManager.GetString("Tarifas_TipoTarifas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NA.
        /// </summary>
        internal static string TipoComponente_NA {
            get {
                return ResourceManager.GetString("TipoComponente_NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encuentra configurada la unidad para la fecha de vigencia {0} del manual {1}.
        /// </summary>
        internal static string UnidadVenta {
            get {
                return ResourceManager.GetString("UnidadVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No fue posible realizar la asociación de ventas, vuelva  a intentarlo nuevamente.
        /// </summary>
        internal static string VentasProductoRelacion {
            get {
                return ResourceManager.GetString("VentasProductoRelacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se presentó un error al insertar las vigencias de tarifa..
        /// </summary>
        internal static string VigenciaTarifa_MsjErrCrearVigencias {
            get {
                return ResourceManager.GetString("VigenciaTarifa_MsjErrCrearVigencias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No fue posible realizar la vinculación del Venta {0} Atención Padre {1} Atención Hija {2}.
        /// </summary>
        internal static string VinculacionVentas {
            get {
                return ResourceManager.GetString("VinculacionVentas", resourceCulture);
            }
        }
    }
}
