//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AdministradorFacPaquetes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdministradorFacPaquetes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.AdministradorFacPaquetes", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relacionar Ventas a la atención actual.
        /// </summary>
        internal static string BotonRelacionar {
            get {
                return ResourceManager.GetString("BotonRelacionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurar Paquetes.
        /// </summary>
        internal static string BtnConfigPaquete {
            get {
                return ResourceManager.GetString("BtnConfigPaquete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paquete.
        /// </summary>
        internal static string BtnPaquete {
            get {
                return ResourceManager.GetString("BtnPaquete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relacionar ventas a la atención actual.
        /// </summary>
        internal static string BtnRelacionarVentas {
            get {
                return ResourceManager.GetString("BtnRelacionarVentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sección.
        /// </summary>
        internal static string CampoSeccion {
            get {
                return ResourceManager.GetString("CampoSeccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definir Condiciones.
        /// </summary>
        internal static string DefinirCondiciones_Titulo {
            get {
                return ResourceManager.GetString("DefinirCondiciones_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definir Cubrimientos.
        /// </summary>
        internal static string DefinirCubrimientos_Titulo {
            get {
                return ResourceManager.GetString("DefinirCubrimientos_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReporteEstadoCuentaMultiple.aspx.
        /// </summary>
        internal static string FacPaquetes_ReporteEstadoCuenta {
            get {
                return ResourceManager.GetString("FacPaquetes_ReporteEstadoCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~\ReportesFacturacion\FacturacionAgrupadaPaquetes.rdlc.
        /// </summary>
        internal static string FacPaquetes_RptEstadoCuentaAgrupado {
            get {
                return ResourceManager.GetString("FacPaquetes_RptEstadoCuentaAgrupado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~\ReportesFacturacion\FacturacionDetalladaPaquetes.rdlc.
        /// </summary>
        internal static string FacPaquetes_RptEstadoCuentaDetallado {
            get {
                return ResourceManager.GetString("FacPaquetes_RptEstadoCuentaDetallado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar Cambios.
        /// </summary>
        internal static string GuardarCambios {
            get {
                return ResourceManager.GetString("GuardarCambios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar Movimientos Activos.
        /// </summary>
        internal static string GuardarMovimientos {
            get {
                return ResourceManager.GetString("GuardarMovimientos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movimientos Activos.
        /// </summary>
        internal static string MovimientosActivos {
            get {
                return ResourceManager.GetString("MovimientosActivos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha realizado la actualización de los movimientos.
        /// </summary>
        internal static string MsjActualizoMovimiento {
            get {
                return ResourceManager.GetString("MsjActualizoMovimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha realizado la actualización de los movimientos.
        /// </summary>
        internal static string MsjNoActualizoMovimiento {
            get {
                return ResourceManager.GetString("MsjNoActualizoMovimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paciente.
        /// </summary>
        internal static string NombrePaciente {
            get {
                return ResourceManager.GetString("NombrePaciente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atención.
        /// </summary>
        internal static string NroAtencion {
            get {
                return ResourceManager.GetString("NroAtencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número documento.
        /// </summary>
        internal static string NroDoc {
            get {
                return ResourceManager.GetString("NroDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entidades.
        /// </summary>
        internal static string TabEntidades {
            get {
                return ResourceManager.GetString("TabEntidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paquetes.
        /// </summary>
        internal static string TabPaquete {
            get {
                return ResourceManager.GetString("TabPaquete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tercero / Cliente.
        /// </summary>
        internal static string TabResponsable {
            get {
                return ResourceManager.GetString("TabResponsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ventas.
        /// </summary>
        internal static string TabVentas {
            get {
                return ResourceManager.GetString("TabVentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de atención.
        /// </summary>
        internal static string TipoAtencion {
            get {
                return ResourceManager.GetString("TipoAtencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo movimiento factura.
        /// </summary>
        internal static string TipoMovFac {
            get {
                return ResourceManager.GetString("TipoMovFac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facturación por Paquetes.
        /// </summary>
        internal static string Titulo {
            get {
                return ResourceManager.GetString("Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vincular Entidad.
        /// </summary>
        internal static string VincularEntidad {
            get {
                return ResourceManager.GetString("VincularEntidad", resourceCulture);
            }
        }
    }
}
