//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AdministradorFacRelacion {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdministradorFacRelacion() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.AdministradorFacRelacion", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizar Información &gt;&gt;.
        /// </summary>
        internal static string FacRelacion_ActualizarInformacion {
            get {
                return ResourceManager.GetString("FacRelacion_ActualizarInformacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AdministradorFacActividadDepositos.aspx.
        /// </summary>
        internal static string FacRelacion_AdministradorFacActividadDepositos {
            get {
                return ResourceManager.GetString("FacRelacion_AdministradorFacActividadDepositos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atenciones.
        /// </summary>
        internal static string FacRelacion_Atenciones {
            get {
                return ResourceManager.GetString("FacRelacion_Atenciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existen {0} atencion(es) que se encuentran en proceso de facturación..
        /// </summary>
        internal static string FacRelacion_AtencionesProceso {
            get {
                return ResourceManager.GetString("FacRelacion_AtencionesProceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recalcular Todas.
        /// </summary>
        internal static string FacRelacion_ChkRecalcularTodas {
            get {
                return ResourceManager.GetString("FacRelacion_ChkRecalcularTodas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar.
        /// </summary>
        internal static string FacRelacion_ChkSeleccionar {
            get {
                return ResourceManager.GetString("FacRelacion_ChkSeleccionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar Todas.
        /// </summary>
        internal static string FacRelacion_ChkSeleccionarTodas {
            get {
                return ResourceManager.GetString("FacRelacion_ChkSeleccionarTodas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Estado de Cuenta &gt;&gt;.
        /// </summary>
        internal static string FacRelacion_ConsultarEstadoCuenta {
            get {
                return ResourceManager.GetString("FacRelacion_ConsultarEstadoCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrato:.
        /// </summary>
        internal static string FacRelacion_Contrato {
            get {
                return ResourceManager.GetString("FacRelacion_Contrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entidad:.
        /// </summary>
        internal static string FacRelacion_Entidad {
            get {
                return ResourceManager.GetString("FacRelacion_Entidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Desde:.
        /// </summary>
        internal static string FacRelacion_FechaDesde {
            get {
                return ResourceManager.GetString("FacRelacion_FechaDesde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Hasta:.
        /// </summary>
        internal static string FacRelacion_FechaHasta {
            get {
                return ResourceManager.GetString("FacRelacion_FechaHasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato:.
        /// </summary>
        internal static string FacRelacion_Formato {
            get {
                return ResourceManager.GetString("FacRelacion_Formato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cruzar.
        /// </summary>
        internal static string FacRelacion_GrvChkCruzar {
            get {
                return ResourceManager.GetString("FacRelacion_GrvChkCruzar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diferencia.
        /// </summary>
        internal static string FacRelacion_GrvChkDiferencia {
            get {
                return ResourceManager.GetString("FacRelacion_GrvChkDiferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facturar.
        /// </summary>
        internal static string FacRelacion_GrvChkFacturar {
            get {
                return ResourceManager.GetString("FacRelacion_GrvChkFacturar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recalcular.
        /// </summary>
        internal static string FacRelacion_GrvChkRecalcular {
            get {
                return ResourceManager.GetString("FacRelacion_GrvChkRecalcular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción del Plan.
        /// </summary>
        internal static string FacRelacion_GrvDescripcionPlan {
            get {
                return ResourceManager.GetString("FacRelacion_GrvDescripcionPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id. Atención.
        /// </summary>
        internal static string FacRelacion_GrvIdAtencion {
            get {
                return ResourceManager.GetString("FacRelacion_GrvIdAtencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre del Grupo.
        /// </summary>
        internal static string FacRelacion_GrvNombreGrupo {
            get {
                return ResourceManager.GetString("FacRelacion_GrvNombreGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre del Producto.
        /// </summary>
        internal static string FacRelacion_GrvNombreProducto {
            get {
                return ResourceManager.GetString("FacRelacion_GrvNombreProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre Tipo de Atención.
        /// </summary>
        internal static string FacRelacion_GrvNombreTipoAtencion {
            get {
                return ResourceManager.GetString("FacRelacion_GrvNombreTipoAtencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre Tipo de Producto.
        /// </summary>
        internal static string FacRelacion_GrvNombreTipoProducto {
            get {
                return ResourceManager.GetString("FacRelacion_GrvNombreTipoProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. del Documento.
        /// </summary>
        internal static string FacRelacion_GrvNumeroDocumento {
            get {
                return ResourceManager.GetString("FacRelacion_GrvNumeroDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paciente.
        /// </summary>
        internal static string FacRelacion_GrvPaciente {
            get {
                return ResourceManager.GetString("FacRelacion_GrvPaciente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Componente.
        /// </summary>
        internal static string FacRelacion_GrvTipoComponente {
            get {
                return ResourceManager.GetString("FacRelacion_GrvTipoComponente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor concepto de cobro.
        /// </summary>
        internal static string FacRelacion_GrvValorConceptoCobro {
            get {
                return ResourceManager.GetString("FacRelacion_GrvValorConceptoCobro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor depósito paciente.
        /// </summary>
        internal static string FacRelacion_GrvValorDepositoPaciente {
            get {
                return ResourceManager.GetString("FacRelacion_GrvValorDepositoPaciente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generar Factura &gt;&gt;.
        /// </summary>
        internal static string FacRelacion_GuardarFacturacion {
            get {
                return ResourceManager.GetString("FacRelacion_GuardarFacturacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movimiento Factura:.
        /// </summary>
        internal static string FacRelacion_MovFactura {
            get {
                return ResourceManager.GetString("FacRelacion_MovFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De las atenciones seleccionadas, ya existe al menos una facturada. Por favor actualizar nuevamente la búsqueda.
        /// </summary>
        internal static string FacRelacion_MsjValidacionAtenciones {
            get {
                return ResourceManager.GetString("FacRelacion_MsjValidacionAtenciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observaciones:.
        /// </summary>
        internal static string FacRelacion_Observaciones {
            get {
                return ResourceManager.GetString("FacRelacion_Observaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planes:.
        /// </summary>
        internal static string FacRelacion_Planes {
            get {
                return ResourceManager.GetString("FacRelacion_Planes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReporteEstadoCuenta.aspx.
        /// </summary>
        internal static string FacRelacion_ReporteEstadoCuenta {
            get {
                return ResourceManager.GetString("FacRelacion_ReporteEstadoCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~\ReportesFacturacion\FacturacionAgrupada.rdlc.
        /// </summary>
        internal static string FacRelacion_RptEstadoCuentaAgrupado {
            get {
                return ResourceManager.GetString("FacRelacion_RptEstadoCuentaAgrupado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~\ReportesFacturacion\FacturacionDetallada.rdlc.
        /// </summary>
        internal static string FacRelacion_RptEstadoCuentaDetallado {
            get {
                return ResourceManager.GetString("FacRelacion_RptEstadoCuentaDetallado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~\ReportesFacturacion\FacturacionResumen.rdlc.
        /// </summary>
        internal static string FacRelacion_RptEstadoCuentaResumen {
            get {
                return ResourceManager.GetString("FacRelacion_RptEstadoCuentaResumen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sección:.
        /// </summary>
        internal static string FacRelacion_Seccion {
            get {
                return ResourceManager.GetString("FacRelacion_Seccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Atención:.
        /// </summary>
        internal static string FacRelacion_TipoAtencion {
            get {
                return ResourceManager.GetString("FacRelacion_TipoAtencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facturación en Relación por Actividades.
        /// </summary>
        internal static string FacRelacion_Titulo {
            get {
                return ResourceManager.GetString("FacRelacion_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de atenciones seleccionadas:.
        /// </summary>
        internal static string FacRelacion_TotalAtencionesSeleccionadas {
            get {
                return ResourceManager.GetString("FacRelacion_TotalAtencionesSeleccionadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total conceptos de cobro:.
        /// </summary>
        internal static string FacRelacion_TotalConceptosCruzados {
            get {
                return ResourceManager.GetString("FacRelacion_TotalConceptosCruzados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total depósitos pacientes:.
        /// </summary>
        internal static string FacRelacion_TotalDepositos {
            get {
                return ResourceManager.GetString("FacRelacion_TotalDepositos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ubicación:.
        /// </summary>
        internal static string FacRelacion_Ubicacion {
            get {
                return ResourceManager.GetString("FacRelacion_Ubicacion", resourceCulture);
            }
        }
    }
}
