//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AdministradorFacActividades {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdministradorFacActividades() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.AdministradorFacActividades", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atención:.
        /// </summary>
        internal static string FacActividad_Atencion {
            get {
                return ResourceManager.GetString("FacActividad_Atencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facturar.
        /// </summary>
        internal static string FacActividad_ChkFacturar {
            get {
                return ResourceManager.GetString("FacActividad_ChkFacturar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generar.
        /// </summary>
        internal static string FacActividad_ChkGenerar {
            get {
                return ResourceManager.GetString("FacActividad_ChkGenerar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar.
        /// </summary>
        internal static string FacActividad_ChkSeleccionar {
            get {
                return ResourceManager.GetString("FacActividad_ChkSeleccionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CortesFacturacion.aspx.
        /// </summary>
        internal static string FacActividad_CortesFacturacion {
            get {
                return ResourceManager.GetString("FacActividad_CortesFacturacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        internal static string FacActividad_GrvChkActivo {
            get {
                return ResourceManager.GetString("FacActividad_GrvChkActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facturar.
        /// </summary>
        internal static string FacActividad_GrvChkFacturar {
            get {
                return ResourceManager.GetString("FacActividad_GrvChkFacturar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generar.
        /// </summary>
        internal static string FacActividad_GrvChkGenerar {
            get {
                return ResourceManager.GetString("FacActividad_GrvChkGenerar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar.
        /// </summary>
        internal static string FacActividad_GrvChkSeleccionar {
            get {
                return ResourceManager.GetString("FacActividad_GrvChkSeleccionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrato.
        /// </summary>
        internal static string FacActividad_GrvEntidad_Contrato {
            get {
                return ResourceManager.GetString("FacActividad_GrvEntidad_Contrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entidad.
        /// </summary>
        internal static string FacActividad_GrvEntidad_Entidad {
            get {
                return ResourceManager.GetString("FacActividad_GrvEntidad_Entidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string FacActividad_GrvEntidad_ID {
            get {
                return ResourceManager.GetString("FacActividad_GrvEntidad_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id Atención.
        /// </summary>
        internal static string FacActividad_GrvEntidad_IdAtencion {
            get {
                return ResourceManager.GetString("FacActividad_GrvEntidad_IdAtencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Plan.
        /// </summary>
        internal static string FacActividad_GrvEntidad_IdPlan {
            get {
                return ResourceManager.GetString("FacActividad_GrvEntidad_IdPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observación.
        /// </summary>
        internal static string FacActividad_GrvEntidad_Observacion {
            get {
                return ResourceManager.GetString("FacActividad_GrvEntidad_Observacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orden.
        /// </summary>
        internal static string FacActividad_GrvEntidad_Orden {
            get {
                return ResourceManager.GetString("FacActividad_GrvEntidad_Orden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan.
        /// </summary>
        internal static string FacActividad_GrvEntidad_Plan {
            get {
                return ResourceManager.GetString("FacActividad_GrvEntidad_Plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atención Enlazada.
        /// </summary>
        internal static string FacActividad_GrvVentas_AtencionEnlazada {
            get {
                return ResourceManager.GetString("FacActividad_GrvVentas_AtencionEnlazada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Venta.
        /// </summary>
        internal static string FacActividad_GrvVentas_FechaVenta {
            get {
                return ResourceManager.GetString("FacActividad_GrvVentas_FechaVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero de Venta.
        /// </summary>
        internal static string FacActividad_GrvVentas_NumeroVenta {
            get {
                return ResourceManager.GetString("FacActividad_GrvVentas_NumeroVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transacción.
        /// </summary>
        internal static string FacActividad_GrvVentas_Transaccion {
            get {
                return ResourceManager.GetString("FacActividad_GrvVentas_Transaccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ubicación de Consumo.
        /// </summary>
        internal static string FacActividad_GrvVentas_UbicacionConsumo {
            get {
                return ResourceManager.GetString("FacActividad_GrvVentas_UbicacionConsumo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ubicación de Entrega.
        /// </summary>
        internal static string FacActividad_GrvVentas_UbicacionEntrega {
            get {
                return ResourceManager.GetString("FacActividad_GrvVentas_UbicacionEntrega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar Movimientos Activos.
        /// </summary>
        internal static string FacActividad_GuardarMovimientos {
            get {
                return ResourceManager.GetString("FacActividad_GuardarMovimientos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movimientos Activos.
        /// </summary>
        internal static string FacActividad_MovimientosActivos {
            get {
                return ResourceManager.GetString("FacActividad_MovimientosActivos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha realizado la actualización de los movimientos.
        /// </summary>
        internal static string FacActividad_MsjActualizoMovimiento {
            get {
                return ResourceManager.GetString("FacActividad_MsjActualizoMovimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha realizado la actualización de los movimientos.
        /// </summary>
        internal static string FacActividad_MsjNoActualizoMovimiento {
            get {
                return ResourceManager.GetString("FacActividad_MsjNoActualizoMovimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. Documento:.
        /// </summary>
        internal static string FacActividad_NoDocumento {
            get {
                return ResourceManager.GetString("FacActividad_NoDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paciente:.
        /// </summary>
        internal static string FacActividad_Paciente {
            get {
                return ResourceManager.GetString("FacActividad_Paciente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pestaña - Entidades.
        /// </summary>
        internal static string FacActividad_PestanaEntidades {
            get {
                return ResourceManager.GetString("FacActividad_PestanaEntidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pestaña - Ventas.
        /// </summary>
        internal static string FacActividad_PestanaVentas {
            get {
                return ResourceManager.GetString("FacActividad_PestanaVentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReporteEstadoCuentaMultiple.aspx.
        /// </summary>
        internal static string FacActividad_ReporteEstadoCuenta {
            get {
                return ResourceManager.GetString("FacActividad_ReporteEstadoCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~\ReportesFacturacion\FacturacionAgrupadaActividades.rdlc.
        /// </summary>
        internal static string FacActividad_RptEstadoCuentaAgrupado {
            get {
                return ResourceManager.GetString("FacActividad_RptEstadoCuentaAgrupado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~\ReportesFacturacion\FacturacionDetalladaActividades.rdlc.
        /// </summary>
        internal static string FacActividad_RptEstadoCuentaDetallado {
            get {
                return ResourceManager.GetString("FacActividad_RptEstadoCuentaDetallado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~\ReportesFacturacion\FacturacionAgrupadaPaquetes.rdlc.
        /// </summary>
        internal static string FacActividad_RptEstadoCuentaPaquetesAgrupado {
            get {
                return ResourceManager.GetString("FacActividad_RptEstadoCuentaPaquetesAgrupado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~\ReportesFacturacion\ReimpresionAgrupadaActividades.rdlc.
        /// </summary>
        internal static string FacActividad_RptEstadoReimpresionCuentaAgrup {
            get {
                return ResourceManager.GetString("FacActividad_RptEstadoReimpresionCuentaAgrup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~\ReportesFacturacion\ReimpresionDetalladaActividades.rdlc.
        /// </summary>
        internal static string FacActividad_RptEstadoReimpresionCuentaDetallado {
            get {
                return ResourceManager.GetString("FacActividad_RptEstadoReimpresionCuentaDetallado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sección:.
        /// </summary>
        internal static string FacActividad_Seccion {
            get {
                return ResourceManager.GetString("FacActividad_Seccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entidades.
        /// </summary>
        internal static string FacActividad_TabEntidades {
            get {
                return ResourceManager.GetString("FacActividad_TabEntidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tercero / Cliente.
        /// </summary>
        internal static string FacActividad_TabResponsable {
            get {
                return ResourceManager.GetString("FacActividad_TabResponsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ventas.
        /// </summary>
        internal static string FacActividad_TabVentas {
            get {
                return ResourceManager.GetString("FacActividad_TabVentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de atención.
        /// </summary>
        internal static string FacActividad_TipoAtencion {
            get {
                return ResourceManager.GetString("FacActividad_TipoAtencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo movimiento factura:.
        /// </summary>
        internal static string FacActividad_TipoMovimientoFactura {
            get {
                return ResourceManager.GetString("FacActividad_TipoMovimientoFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facturación por Actividades.
        /// </summary>
        internal static string FacActividad_Titulo {
            get {
                return ResourceManager.GetString("FacActividad_Titulo", resourceCulture);
            }
        }
    }
}
