//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CondicionesCubrimientos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CondicionesCubrimientos() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.CondicionesCubrimientos", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        internal static string CondicionesCubrimientos_Activo {
            get {
                return ResourceManager.GetString("CondicionesCubrimientos_Activo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Condición de Cubrimiento.
        /// </summary>
        internal static string CondicionesCubrimientos_Actualizar {
            get {
                return ResourceManager.GetString("CondicionesCubrimientos_Actualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar.
        /// </summary>
        internal static string CondicionesCubrimientos_BtnAdicionar {
            get {
                return ResourceManager.GetString("CondicionesCubrimientos_BtnAdicionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adiciona.
        /// </summary>
        internal static string CondicionesCubrimientos_BtnAdicionarToolTip {
            get {
                return ResourceManager.GetString("CondicionesCubrimientos_BtnAdicionarToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar.
        /// </summary>
        internal static string CondicionesCubrimientos_BtnConsultar {
            get {
                return ResourceManager.GetString("CondicionesCubrimientos_BtnConsultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consulta.
        /// </summary>
        internal static string CondicionesCubrimientos_BtnConsultarToolTip {
            get {
                return ResourceManager.GetString("CondicionesCubrimientos_BtnConsultarToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar.
        /// </summary>
        internal static string CondicionesCubrimientos_BtnModificar {
            get {
                return ResourceManager.GetString("CondicionesCubrimientos_BtnModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifica.
        /// </summary>
        internal static string CondicionesCubrimientos_BtnModificarToolTip {
            get {
                return ResourceManager.GetString("CondicionesCubrimientos_BtnModificarToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clase Cubrimiento.
        /// </summary>
        internal static string CondicionesCubrimientos_ClaseCubrimiento {
            get {
                return ResourceManager.GetString("CondicionesCubrimientos_ClaseCubrimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clase de Servicio.
        /// </summary>
        internal static string CondicionesCubrimientos_ClaseServicio {
            get {
                return ResourceManager.GetString("CondicionesCubrimientos_ClaseServicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Componente.
        /// </summary>
        internal static string CondicionesCubrimientos_Componente {
            get {
                return ResourceManager.GetString("CondicionesCubrimientos_Componente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condición Activa.
        /// </summary>
        internal static string CondicionesCubrimientos_CondicionActiva {
            get {
                return ResourceManager.GetString("CondicionesCubrimientos_CondicionActiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consulta Condición de Cubrimiento.
        /// </summary>
        internal static string CondicionesCubrimientos_Consultar {
            get {
                return ResourceManager.GetString("CondicionesCubrimientos_Consultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrato .
        /// </summary>
        internal static string CondicionesCubrimientos_Contrato {
            get {
                return ResourceManager.GetString("CondicionesCubrimientos_Contrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Condición de Cubrimiento.
        /// </summary>
        internal static string CondicionesCubrimientos_Crear {
            get {
                return ResourceManager.GetString("CondicionesCubrimientos_Crear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cubrimiento.
        /// </summary>
        internal static string CondicionesCubrimientos_Cubrimiento {
            get {
                return ResourceManager.GetString("CondicionesCubrimientos_Cubrimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        internal static string CondicionesCubrimientos_Descripcion {
            get {
                return ResourceManager.GetString("CondicionesCubrimientos_Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entidad.
        /// </summary>
        internal static string CondicionesCubrimientos_Entidad {
            get {
                return ResourceManager.GetString("CondicionesCubrimientos_Entidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Final.
        /// </summary>
        internal static string CondicionesCubrimientos_FechaFinal {
            get {
                return ResourceManager.GetString("CondicionesCubrimientos_FechaFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Inicial.
        /// </summary>
        internal static string CondicionesCubrimientos_FechaInicial {
            get {
                return ResourceManager.GetString("CondicionesCubrimientos_FechaInicial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo de Producto.
        /// </summary>
        internal static string CondicionesCubrimientos_GrupoProducto {
            get {
                return ResourceManager.GetString("CondicionesCubrimientos_GrupoProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID  Atencion.
        /// </summary>
        internal static string CondicionesCubrimientos_IAtencion {
            get {
                return ResourceManager.GetString("CondicionesCubrimientos_IAtencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Cond. Cubrimiento.
        /// </summary>
        internal static string CondicionesCubrimientos_IdCondicionCubrimiento {
            get {
                return ResourceManager.GetString("CondicionesCubrimientos_IdCondicionCubrimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Descuentos.
        /// </summary>
        internal static string CondicionesCubrimientos_IdDescuento {
            get {
                return ResourceManager.GetString("CondicionesCubrimientos_IdDescuento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificador.
        /// </summary>
        internal static string CondicionesCubrimientos_Identificador {
            get {
                return ResourceManager.GetString("CondicionesCubrimientos_Identificador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan.
        /// </summary>
        internal static string CondicionesCubrimientos_Plan {
            get {
                return ResourceManager.GetString("CondicionesCubrimientos_Plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Atención.
        /// </summary>
        internal static string CondicionesCubrimientos_TipoAtencion {
            get {
                return ResourceManager.GetString("CondicionesCubrimientos_TipoAtencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Relacion.
        /// </summary>
        internal static string CondicionesCubrimientos_TipoRelacion {
            get {
                return ResourceManager.GetString("CondicionesCubrimientos_TipoRelacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descuentos.
        /// </summary>
        internal static string CondicionesCubrimientos_Titulo {
            get {
                return ResourceManager.GetString("CondicionesCubrimientos_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor.
        /// </summary>
        internal static string CondicionesCubrimientos_Valor {
            get {
                return ResourceManager.GetString("CondicionesCubrimientos_Valor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Descuentos.
        /// </summary>
        internal static string CondicionesCubrimientos_ValorDescuentos {
            get {
                return ResourceManager.GetString("CondicionesCubrimientos_ValorDescuentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vigencia de Condición.
        /// </summary>
        internal static string CondicionesCubrimientos_VigenciaCondicion {
            get {
                return ResourceManager.GetString("CondicionesCubrimientos_VigenciaCondicion", resourceCulture);
            }
        }
    }
}
