//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CondicionesFacturacion {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CondicionesFacturacion() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.CondicionesFacturacion", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodIndAct.
        /// </summary>
        internal static string CondicionesFacturacion_Activo {
            get {
                return ResourceManager.GetString("CondicionesFacturacion_Activo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id. Atencion.
        /// </summary>
        internal static string CondicionesFacturacion_Atencion {
            get {
                return ResourceManager.GetString("CondicionesFacturacion_Atencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        internal static string CondicionesFacturacion_CActivo {
            get {
                return ResourceManager.GetString("CondicionesFacturacion_CActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activa o desactiva la condición de facturación.
        /// </summary>
        internal static string CondicionesFacturacion_ChkActivo {
            get {
                return ResourceManager.GetString("CondicionesFacturacion_ChkActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible ejecutar esta accion , existe Una Condición de Facturación Activa para esta atención!.
        /// </summary>
        internal static string CondicionesFacturacion_conficuracionExistente {
            get {
                return ResourceManager.GetString("CondicionesFacturacion_conficuracionExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrato.
        /// </summary>
        internal static string CondicionesFacturacion_Contrato {
            get {
                return ResourceManager.GetString("CondicionesFacturacion_Contrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entidad.
        /// </summary>
        internal static string CondicionesFacturacion_Entidad {
            get {
                return ResourceManager.GetString("CondicionesFacturacion_Entidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan.
        /// </summary>
        internal static string CondicionesFacturacion_Plan {
            get {
                return ResourceManager.GetString("CondicionesFacturacion_Plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Relación.
        /// </summary>
        internal static string CondicionesFacturacion_TipoRelacion {
            get {
                return ResourceManager.GetString("CondicionesFacturacion_TipoRelacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condiciones de Facturación.
        /// </summary>
        internal static string CondicionesFacturacion_Titulo {
            get {
                return ResourceManager.GetString("CondicionesFacturacion_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizar Condición de Facturación.
        /// </summary>
        internal static string CondicionesFacturacion_TituloActualizar {
            get {
                return ResourceManager.GetString("CondicionesFacturacion_TituloActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consulta Condición de Facturación.
        /// </summary>
        internal static string CondicionesFacturacion_TituloConsulta {
            get {
                return ResourceManager.GetString("CondicionesFacturacion_TituloConsulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Condición de Facturación.
        /// </summary>
        internal static string CondicionesFacturacion_TituloCrear {
            get {
                return ResourceManager.GetString("CondicionesFacturacion_TituloCrear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Condición de Facturación.
        /// </summary>
        internal static string CondicionesFacturacion_TituloModificar {
            get {
                return ResourceManager.GetString("CondicionesFacturacion_TituloModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        internal static string FacActividad_GrvCondicionesFacturacion_Descripcion {
            get {
                return ResourceManager.GetString("FacActividad_GrvCondicionesFacturacion_Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificación Atención.
        /// </summary>
        internal static string FacActividad_GrvCondicionesFacturacion_IdAtencion {
            get {
                return ResourceManager.GetString("FacActividad_GrvCondicionesFacturacion_IdAtencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.
        /// </summary>
        internal static string FacActividad_GrvCondicionesFacturacion_Tipo {
            get {
                return ResourceManager.GetString("FacActividad_GrvCondicionesFacturacion_Tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Relación.
        /// </summary>
        internal static string FacActividad_GrvCondicionesFacturacion_TipoRelacion {
            get {
                return ResourceManager.GetString("FacActividad_GrvCondicionesFacturacion_TipoRelacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor.
        /// </summary>
        internal static string FacActividad_GrvCondicionesFacturacion_Valor {
            get {
                return ResourceManager.GetString("FacActividad_GrvCondicionesFacturacion_Valor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vigencia.
        /// </summary>
        internal static string FacActividad_GrvCondicionesFacturacion_Vigencia {
            get {
                return ResourceManager.GetString("FacActividad_GrvCondicionesFacturacion_Vigencia", resourceCulture);
            }
        }
    }
}
