//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CortesFacturacion {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CortesFacturacion() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.CortesFacturacion", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar.
        /// </summary>
        internal static string CortesFacturacion_BtnAdicionar {
            get {
                return ResourceManager.GetString("CortesFacturacion_BtnAdicionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar Corte.
        /// </summary>
        internal static string CortesFacturacion_BtnAdicionarToolTip {
            get {
                return ResourceManager.GetString("CortesFacturacion_BtnAdicionarToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salir.
        /// </summary>
        internal static string CortesFacturacion_BtnSalir {
            get {
                return ResourceManager.GetString("CortesFacturacion_BtnSalir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salir.
        /// </summary>
        internal static string CortesFacturacion_BtnSalirToolTip {
            get {
                return ResourceManager.GetString("CortesFacturacion_BtnSalirToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Desde:.
        /// </summary>
        internal static string CortesFacturacion_FechaDesde {
            get {
                return ResourceManager.GetString("CortesFacturacion_FechaDesde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Hasta:.
        /// </summary>
        internal static string CortesFacturacion_FechaHasta {
            get {
                return ResourceManager.GetString("CortesFacturacion_FechaHasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar Corte.
        /// </summary>
        internal static string CortesFacturacion_GrvBtnSeleccionarToolTip {
            get {
                return ResourceManager.GetString("CortesFacturacion_GrvBtnSeleccionarToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar.
        /// </summary>
        internal static string CortesFacturacion_GrvChkSeleccionar {
            get {
                return ResourceManager.GetString("CortesFacturacion_GrvChkSeleccionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Final.
        /// </summary>
        internal static string CortesFacturacion_GrvFechaFinal {
            get {
                return ResourceManager.GetString("CortesFacturacion_GrvFechaFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Inicial.
        /// </summary>
        internal static string CortesFacturacion_GrvFechaInicial {
            get {
                return ResourceManager.GetString("CortesFacturacion_GrvFechaInicial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        internal static string CortesFacturacion_GrvLblEliminar {
            get {
                return ResourceManager.GetString("CortesFacturacion_GrvLblEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar Corte.
        /// </summary>
        internal static string CortesFacturacion_GrvLblEliminarToolTip {
            get {
                return ResourceManager.GetString("CortesFacturacion_GrvLblEliminarToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definir Cortes de Facturación por rango de fecha.
        /// </summary>
        internal static string CortesFacturacion_Titulo {
            get {
                return ResourceManager.GetString("CortesFacturacion_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cortes Definidos.
        /// </summary>
        internal static string CortesFacturacion_TituloGrilla {
            get {
                return ResourceManager.GetString("CortesFacturacion_TituloGrilla", resourceCulture);
            }
        }
    }
}
