//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DefinirExclusiones {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DefinirExclusiones() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DefinirExclusiones", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        internal static string DefinirExclusiones_Activo {
            get {
                return ResourceManager.GetString("DefinirExclusiones_Activo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizar Exclusión.
        /// </summary>
        internal static string DefinirExclusiones_Actualizar {
            get {
                return ResourceManager.GetString("DefinirExclusiones_Actualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterno.
        /// </summary>
        internal static string DefinirExclusiones_Alterno {
            get {
                return ResourceManager.GetString("DefinirExclusiones_Alterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atención No..
        /// </summary>
        internal static string DefinirExclusiones_AtencionNo {
            get {
                return ResourceManager.GetString("DefinirExclusiones_AtencionNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar.
        /// </summary>
        internal static string DefinirExclusiones_BtnAdicionar {
            get {
                return ResourceManager.GetString("DefinirExclusiones_BtnAdicionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva Exclusión.
        /// </summary>
        internal static string DefinirExclusiones_BtnAdicionarToolTip {
            get {
                return ResourceManager.GetString("DefinirExclusiones_BtnAdicionarToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar.
        /// </summary>
        internal static string DefinirExclusiones_BtnConsultar {
            get {
                return ResourceManager.GetString("DefinirExclusiones_BtnConsultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar.
        /// </summary>
        internal static string DefinirExclusiones_BtnConsultarToolTip {
            get {
                return ResourceManager.GetString("DefinirExclusiones_BtnConsultarToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Componente.
        /// </summary>
        internal static string DefinirExclusiones_Componente {
            get {
                return ResourceManager.GetString("DefinirExclusiones_Componente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Exclusion.
        /// </summary>
        internal static string DefinirExclusiones_Consultar {
            get {
                return ResourceManager.GetString("DefinirExclusiones_Consultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrato.
        /// </summary>
        internal static string DefinirExclusiones_Contrato {
            get {
                return ResourceManager.GetString("DefinirExclusiones_Contrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Exclusión.
        /// </summary>
        internal static string DefinirExclusiones_Crear {
            get {
                return ResourceManager.GetString("DefinirExclusiones_Crear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entidad.
        /// </summary>
        internal static string DefinirExclusiones_Entidad {
            get {
                return ResourceManager.GetString("DefinirExclusiones_Entidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo de Producto.
        /// </summary>
        internal static string DefinirExclusiones_GrupoProducto {
            get {
                return ResourceManager.GetString("DefinirExclusiones_GrupoProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id. Atención.
        /// </summary>
        internal static string DefinirExclusiones_IdAtencion {
            get {
                return ResourceManager.GetString("DefinirExclusiones_IdAtencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificador Producto Alterno.
        /// </summary>
        internal static string DefinirExclusiones_IdProductoAlterno {
            get {
                return ResourceManager.GetString("DefinirExclusiones_IdProductoAlterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        internal static string DefinirExclusiones_Manual {
            get {
                return ResourceManager.GetString("DefinirExclusiones_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niveles.
        /// </summary>
        internal static string DefinirExclusiones_Niveles {
            get {
                return ResourceManager.GetString("DefinirExclusiones_Niveles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nivel final.
        /// </summary>
        internal static string DefinirExclusiones_NivelFinal {
            get {
                return ResourceManager.GetString("DefinirExclusiones_NivelFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nivel incial.
        /// </summary>
        internal static string DefinirExclusiones_NivelInicial {
            get {
                return ResourceManager.GetString("DefinirExclusiones_NivelInicial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre Tarifa.
        /// </summary>
        internal static string DefinirExclusiones_NombreTarifa {
            get {
                return ResourceManager.GetString("DefinirExclusiones_NombreTarifa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan.
        /// </summary>
        internal static string DefinirExclusiones_Plan {
            get {
                return ResourceManager.GetString("DefinirExclusiones_Plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producto.
        /// </summary>
        internal static string DefinirExclusiones_Producto {
            get {
                return ResourceManager.GetString("DefinirExclusiones_Producto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rango final orden de Nivel.
        /// </summary>
        internal static string DefinirExclusiones_RangoFinalOrdenNivel {
            get {
                return ResourceManager.GetString("DefinirExclusiones_RangoFinalOrdenNivel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rango max. nivel.
        /// </summary>
        internal static string DefinirExclusiones_RangoMaximo {
            get {
                return ResourceManager.GetString("DefinirExclusiones_RangoMaximo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rango min. nivel.
        /// </summary>
        internal static string DefinirExclusiones_RangoMinimo {
            get {
                return ResourceManager.GetString("DefinirExclusiones_RangoMinimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rango de orden de nivel.
        /// </summary>
        internal static string DefinirExclusiones_RangoOrdenNivel {
            get {
                return ResourceManager.GetString("DefinirExclusiones_RangoOrdenNivel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicio.
        /// </summary>
        internal static string DefinirExclusiones_Servicio {
            get {
                return ResourceManager.GetString("DefinirExclusiones_Servicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarifa.
        /// </summary>
        internal static string DefinirExclusiones_Tarifa {
            get {
                return ResourceManager.GetString("DefinirExclusiones_Tarifa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de atención.
        /// </summary>
        internal static string DefinirExclusiones_TipoAtencion {
            get {
                return ResourceManager.GetString("DefinirExclusiones_TipoAtencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Producto.
        /// </summary>
        internal static string DefinirExclusiones_TipoProducto {
            get {
                return ResourceManager.GetString("DefinirExclusiones_TipoProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Relación.
        /// </summary>
        internal static string DefinirExclusiones_TipoRelacion {
            get {
                return ResourceManager.GetString("DefinirExclusiones_TipoRelacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definir Exclusiones.
        /// </summary>
        internal static string DefinirExclusiones_Titulo {
            get {
                return ResourceManager.GetString("DefinirExclusiones_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidad.
        /// </summary>
        internal static string DefinirExclusiones_Unidad {
            get {
                return ResourceManager.GetString("DefinirExclusiones_Unidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venta.
        /// </summary>
        internal static string DefinirExclusiones_Venta {
            get {
                return ResourceManager.GetString("DefinirExclusiones_Venta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vigencia.
        /// </summary>
        internal static string DefinirExclusiones_Vigencia {
            get {
                return ResourceManager.GetString("DefinirExclusiones_Vigencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vigencia Tarifa.
        /// </summary>
        internal static string DefinirExclusiones_VigenciaTarifa {
            get {
                return ResourceManager.GetString("DefinirExclusiones_VigenciaTarifa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo de Producto.
        /// </summary>
        internal static string Definir_Eclusiones_Grupo_Producto {
            get {
                return ResourceManager.GetString("Definir_Eclusiones_Grupo_Producto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clase de Servicio.
        /// </summary>
        internal static string Definir_Exclusiones_Clase_Servicio {
            get {
                return ResourceManager.GetString("Definir_Exclusiones_Clase_Servicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificador.
        /// </summary>
        internal static string Definir_Exclusiones_Identificador {
            get {
                return ResourceManager.GetString("Definir_Exclusiones_Identificador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        internal static string Definir_Exclusiones_Manual {
            get {
                return ResourceManager.GetString("Definir_Exclusiones_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máximo.
        /// </summary>
        internal static string Definir_Exclusiones_Maximo {
            get {
                return ResourceManager.GetString("Definir_Exclusiones_Maximo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mínimo.
        /// </summary>
        internal static string Definir_Exclusiones_Minimo {
            get {
                return ResourceManager.GetString("Definir_Exclusiones_Minimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nivel 2.
        /// </summary>
        internal static string Definir_Exclusiones_NivelDos {
            get {
                return ResourceManager.GetString("Definir_Exclusiones_NivelDos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nivel 1.
        /// </summary>
        internal static string Definir_Exclusiones_NivelUno {
            get {
                return ResourceManager.GetString("Definir_Exclusiones_NivelUno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producto Alterno.
        /// </summary>
        internal static string Definir_Exclusiones_Producto_Alterno {
            get {
                return ResourceManager.GetString("Definir_Exclusiones_Producto_Alterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidades.
        /// </summary>
        internal static string Definir_Exclusiones_Unidades {
            get {
                return ResourceManager.GetString("Definir_Exclusiones_Unidades", resourceCulture);
            }
        }
    }
}
