//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DefinirCondicionesTarifa {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DefinirCondicionesTarifa() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DefinirCondicionesTarifa", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observaciones.
        /// </summary>
        internal static string CondicionesCubrimientos_Descripcion {
            get {
                return ResourceManager.GetString("CondicionesCubrimientos_Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor.
        /// </summary>
        internal static string CondicionesCubrimientos_Valor {
            get {
                return ResourceManager.GetString("CondicionesCubrimientos_Valor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha realizado la actualización de la condición de facturación.
        /// </summary>
        internal static string CondicionFacturacion_MsjActualizacion {
            get {
                return ResourceManager.GetString("CondicionFacturacion_MsjActualizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No fue posible realizar la actualización de la condición de facturación.
        /// </summary>
        internal static string CondicionFacturacion_MsjActualizacionError {
            get {
                return ResourceManager.GetString("CondicionFacturacion_MsjActualizacionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha realizado la creación  de la condición de facturación {0} .
        /// </summary>
        internal static string CondicionFacturacion_MsjInsercion {
            get {
                return ResourceManager.GetString("CondicionFacturacion_MsjInsercion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        internal static string DefinirCondicionesTarifa_Activo {
            get {
                return ResourceManager.GetString("DefinirCondicionesTarifa_Activo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id Atención.
        /// </summary>
        internal static string DefinirCondicionesTarifa_Atencion {
            get {
                return ResourceManager.GetString("DefinirCondicionesTarifa_Atencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar.
        /// </summary>
        internal static string DefinirCondicionesTarifa_BtnModificar {
            get {
                return ResourceManager.GetString("DefinirCondicionesTarifa_BtnModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Componente.
        /// </summary>
        internal static string DefinirCondicionesTarifa_Componente {
            get {
                return ResourceManager.GetString("DefinirCondicionesTarifa_Componente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        internal static string DefinirCondicionesTarifa_CondicionTarifaActiva {
            get {
                return ResourceManager.GetString("DefinirCondicionesTarifa_CondicionTarifaActiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible ejecutar esta acción , existe Una Tarifa con esas mismas caracteristicas!.
        /// </summary>
        internal static string DefinirCondicionesTarifa_ConfiguracionExiste {
            get {
                return ResourceManager.GetString("DefinirCondicionesTarifa_ConfiguracionExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrato.
        /// </summary>
        internal static string DefinirCondicionesTarifa_Contrato {
            get {
                return ResourceManager.GetString("DefinirCondicionesTarifa_Contrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entidad.
        /// </summary>
        internal static string DefinirCondicionesTarifa_Entidad {
            get {
                return ResourceManager.GetString("DefinirCondicionesTarifa_Entidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El producto seleccionado tiene una restricción para tipo relación No cubrimiento con Cantidad, son excluyentes..
        /// </summary>
        internal static string DefinirCondicionesTarifa_Excluyentes {
            get {
                return ResourceManager.GetString("DefinirCondicionesTarifa_Excluyentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo de Producto.
        /// </summary>
        internal static string DefinirCondicionesTarifa_GrupoProducto {
            get {
                return ResourceManager.GetString("DefinirCondicionesTarifa_GrupoProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id. Atención.
        /// </summary>
        internal static string DefinirCondicionesTarifa_IdAtencion {
            get {
                return ResourceManager.GetString("DefinirCondicionesTarifa_IdAtencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificador.
        /// </summary>
        internal static string DefinirCondicionesTarifa_Identificador {
            get {
                return ResourceManager.GetString("DefinirCondicionesTarifa_Identificador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insertar.
        /// </summary>
        internal static string DefinirCondicionesTarifa_Insertar_Operacion {
            get {
                return ResourceManager.GetString("DefinirCondicionesTarifa_Insertar_Operacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar.
        /// </summary>
        internal static string DefinirCondicionesTarifa_Modificar_Operacion {
            get {
                return ResourceManager.GetString("DefinirCondicionesTarifa_Modificar_Operacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha realizado la actualización de la condición de tarifa.
        /// </summary>
        internal static string DefinirCondicionesTarifa_MsjActualizacion {
            get {
                return ResourceManager.GetString("DefinirCondicionesTarifa_MsjActualizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No fue posible realizar la actualización de la condición de tarifa.
        /// </summary>
        internal static string DefinirCondicionesTarifa_MsjActualizacionError {
            get {
                return ResourceManager.GetString("DefinirCondicionesTarifa_MsjActualizacionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha realizado la creación  de la condición de tarifa {0} .
        /// </summary>
        internal static string DefinirCondicionesTarifa_MsjInsercion {
            get {
                return ResourceManager.GetString("DefinirCondicionesTarifa_MsjInsercion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string DefinirCondicionesTarifa_NoCubrimiento {
            get {
                return ResourceManager.GetString("DefinirCondicionesTarifa_NoCubrimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre Grupo Producto.
        /// </summary>
        internal static string DefinirCondicionesTarifa_NombreGrupoProducto {
            get {
                return ResourceManager.GetString("DefinirCondicionesTarifa_NombreGrupoProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre Producto.
        /// </summary>
        internal static string DefinirCondicionesTarifa_NombreProducto {
            get {
                return ResourceManager.GetString("DefinirCondicionesTarifa_NombreProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre Tarifa.
        /// </summary>
        internal static string DefinirCondicionesTarifa_NombreTarifa {
            get {
                return ResourceManager.GetString("DefinirCondicionesTarifa_NombreTarifa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre Tarifa Alterna.
        /// </summary>
        internal static string DefinirCondicionesTarifa_NombreTarifaAlterna {
            get {
                return ResourceManager.GetString("DefinirCondicionesTarifa_NombreTarifaAlterna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan.
        /// </summary>
        internal static string DefinirCondicionesTarifa_Plan {
            get {
                return ResourceManager.GetString("DefinirCondicionesTarifa_Plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producto.
        /// </summary>
        internal static string DefinirCondicionesTarifa_Producto {
            get {
                return ResourceManager.GetString("DefinirCondicionesTarifa_Producto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicio.
        /// </summary>
        internal static string DefinirCondicionesTarifa_Servicio {
            get {
                return ResourceManager.GetString("DefinirCondicionesTarifa_Servicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarifa.
        /// </summary>
        internal static string DefinirCondicionesTarifa_Tarifa {
            get {
                return ResourceManager.GetString("DefinirCondicionesTarifa_Tarifa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarifa Alterna.
        /// </summary>
        internal static string DefinirCondicionesTarifa_TarifaAlterna {
            get {
                return ResourceManager.GetString("DefinirCondicionesTarifa_TarifaAlterna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T.
        /// </summary>
        internal static string DefinirCondicionesTarifa_Tipo {
            get {
                return ResourceManager.GetString("DefinirCondicionesTarifa_Tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Atención.
        /// </summary>
        internal static string DefinirCondicionesTarifa_TipoAtencion {
            get {
                return ResourceManager.GetString("DefinirCondicionesTarifa_TipoAtencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Producto.
        /// </summary>
        internal static string DefinirCondicionesTarifa_TipoProducto {
            get {
                return ResourceManager.GetString("DefinirCondicionesTarifa_TipoProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Relación.
        /// </summary>
        internal static string DefinirCondicionesTarifa_TipoRelacion {
            get {
                return ResourceManager.GetString("DefinirCondicionesTarifa_TipoRelacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definir Condiciones Tarifa.
        /// </summary>
        internal static string DefinirCondicionesTarifa_Titulo {
            get {
                return ResourceManager.GetString("DefinirCondicionesTarifa_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vigencia .
        /// </summary>
        internal static string DefinirCondicionesTarifa_Vigencia {
            get {
                return ResourceManager.GetString("DefinirCondicionesTarifa_Vigencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vigencia Alterna.
        /// </summary>
        internal static string DefinirCondicionesTarifa_VigenciaAlterna {
            get {
                return ResourceManager.GetString("DefinirCondicionesTarifa_VigenciaAlterna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vigencia Condición.
        /// </summary>
        internal static string DefinirCondicionesTarifa_VigenciaCondicion {
            get {
                return ResourceManager.GetString("DefinirCondicionesTarifa_VigenciaCondicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vigencia Tarifa.
        /// </summary>
        internal static string DefinirCondicionesTarifa_VigenciaTarifa {
            get {
                return ResourceManager.GetString("DefinirCondicionesTarifa_VigenciaTarifa", resourceCulture);
            }
        }
    }
}
