//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DefinirCubrimientos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DefinirCubrimientos() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DefinirCubrimientos", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        internal static string DefinirCubrimientos_Activo {
            get {
                return ResourceManager.GetString("DefinirCubrimientos_Activo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizar Cubrimiento.
        /// </summary>
        internal static string DefinirCubrimientos_Actualizar {
            get {
                return ResourceManager.GetString("DefinirCubrimientos_Actualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo.
        /// </summary>
        internal static string DefinirCubrimientos_BtnAdicionar {
            get {
                return ResourceManager.GetString("DefinirCubrimientos_BtnAdicionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo.
        /// </summary>
        internal static string DefinirCubrimientos_BtnAdicionarToolTip {
            get {
                return ResourceManager.GetString("DefinirCubrimientos_BtnAdicionarToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar.
        /// </summary>
        internal static string DefinirCubrimientos_BtnConsultar {
            get {
                return ResourceManager.GetString("DefinirCubrimientos_BtnConsultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar.
        /// </summary>
        internal static string DefinirCubrimientos_BtnConsultarToolTip {
            get {
                return ResourceManager.GetString("DefinirCubrimientos_BtnConsultarToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código Producto.
        /// </summary>
        internal static string DefinirCubrimientos_CodigoProducto {
            get {
                return ResourceManager.GetString("DefinirCubrimientos_CodigoProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Componente.
        /// </summary>
        internal static string DefinirCubrimientos_Componente {
            get {
                return ResourceManager.GetString("DefinirCubrimientos_Componente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar.
        /// </summary>
        internal static string DefinirCubrimientos_Confirmar {
            get {
                return ResourceManager.GetString("DefinirCubrimientos_Confirmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Cubrimiento.
        /// </summary>
        internal static string DefinirCubrimientos_Consultar {
            get {
                return ResourceManager.GetString("DefinirCubrimientos_Consultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrato.
        /// </summary>
        internal static string DefinirCubrimientos_Contrato {
            get {
                return ResourceManager.GetString("DefinirCubrimientos_Contrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Cubrimiento.
        /// </summary>
        internal static string DefinirCubrimientos_Crear {
            get {
                return ResourceManager.GetString("DefinirCubrimientos_Crear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cubrimiento.
        /// </summary>
        internal static string DefinirCubrimientos_Cubrimiento {
            get {
                return ResourceManager.GetString("DefinirCubrimientos_Cubrimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entidad.
        /// </summary>
        internal static string DefinirCubrimientos_Entidad {
            get {
                return ResourceManager.GetString("DefinirCubrimientos_Entidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusion Activa.
        /// </summary>
        internal static string DefinirCubrimientos_ExclusionActiva {
            get {
                return ResourceManager.GetString("DefinirCubrimientos_ExclusionActiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo de Producto.
        /// </summary>
        internal static string DefinirCubrimientos_GrupoProducto {
            get {
                return ResourceManager.GetString("DefinirCubrimientos_GrupoProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id. Atención.
        /// </summary>
        internal static string DefinirCubrimientos_IdAtencion {
            get {
                return ResourceManager.GetString("DefinirCubrimientos_IdAtencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Cubrimiento.
        /// </summary>
        internal static string DefinirCubrimientos_IdCubrimiento {
            get {
                return ResourceManager.GetString("DefinirCubrimientos_IdCubrimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificador.
        /// </summary>
        internal static string DefinirCubrimientos_Identificador {
            get {
                return ResourceManager.GetString("DefinirCubrimientos_Identificador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre del Producto.
        /// </summary>
        internal static string DefinirCubrimientos_NombreProducto {
            get {
                return ResourceManager.GetString("DefinirCubrimientos_NombreProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan.
        /// </summary>
        internal static string DefinirCubrimientos_Plan {
            get {
                return ResourceManager.GetString("DefinirCubrimientos_Plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producto.
        /// </summary>
        internal static string DefinirCubrimientos_Producto {
            get {
                return ResourceManager.GetString("DefinirCubrimientos_Producto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salir.
        /// </summary>
        internal static string DefinirCubrimientos_Salir {
            get {
                return ResourceManager.GetString("DefinirCubrimientos_Salir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Producto.
        /// </summary>
        internal static string DefinirCubrimientos_TipoProducto {
            get {
                return ResourceManager.GetString("DefinirCubrimientos_TipoProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definir Cubrimientos.
        /// </summary>
        internal static string DefinirCubrimientos_Titulo {
            get {
                return ResourceManager.GetString("DefinirCubrimientos_Titulo", resourceCulture);
            }
        }
    }
}
