//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Descuentos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Descuentos() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Descuentos", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        internal static string CondicionesCubrimientos_Descripcion {
            get {
                return ResourceManager.GetString("CondicionesCubrimientos_Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor.
        /// </summary>
        internal static string CondicionesCubrimientos_Valor {
            get {
                return ResourceManager.GetString("CondicionesCubrimientos_Valor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vigencia.
        /// </summary>
        internal static string CondicionesCubrimientos_Vigencia {
            get {
                return ResourceManager.GetString("CondicionesCubrimientos_Vigencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre Tarifa.
        /// </summary>
        internal static string DefinirCondicionesTarifa_NombreTarifa {
            get {
                return ResourceManager.GetString("DefinirCondicionesTarifa_NombreTarifa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definir Condiciones Tarifa.
        /// </summary>
        internal static string DefinirCondicionesTarifa_Titulo {
            get {
                return ResourceManager.GetString("DefinirCondicionesTarifa_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vigencia Condición.
        /// </summary>
        internal static string DefinirCondicionesTarifa_VigenciaCondicion {
            get {
                return ResourceManager.GetString("DefinirCondicionesTarifa_VigenciaCondicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VigenciaTarifa.
        /// </summary>
        internal static string DefinirCondicionesTarifa_VigenciaTarifa {
            get {
                return ResourceManager.GetString("DefinirCondicionesTarifa_VigenciaTarifa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        internal static string Descuentos_Activo {
            get {
                return ResourceManager.GetString("Descuentos_Activo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atención.
        /// </summary>
        internal static string Descuentos_Atencion {
            get {
                return ResourceManager.GetString("Descuentos_Atencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Componente.
        /// </summary>
        internal static string Descuentos_Componente {
            get {
                return ResourceManager.GetString("Descuentos_Componente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible ejecutar esta accion , existe un Descuento con esas mismas caracteristicas!.
        /// </summary>
        internal static string Descuentos_ConfiguracionExiste {
            get {
                return ResourceManager.GetString("Descuentos_ConfiguracionExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Descuento.
        /// </summary>
        internal static string Descuentos_Consultar {
            get {
                return ResourceManager.GetString("Descuentos_Consultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrato .
        /// </summary>
        internal static string Descuentos_Contrato {
            get {
                return ResourceManager.GetString("Descuentos_Contrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Descuento.
        /// </summary>
        internal static string Descuentos_CrearDescuento {
            get {
                return ResourceManager.GetString("Descuentos_CrearDescuento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cubrimiento.
        /// </summary>
        internal static string Descuentos_Cubrimiento {
            get {
                return ResourceManager.GetString("Descuentos_Cubrimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entidad.
        /// </summary>
        internal static string Descuentos_Entidad {
            get {
                return ResourceManager.GetString("Descuentos_Entidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrio un error al cargar la información..
        /// </summary>
        internal static string Descuentos_ErrorCargueInformacion {
            get {
                return ResourceManager.GetString("Descuentos_ErrorCargueInformacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Final.
        /// </summary>
        internal static string Descuentos_FechaFinal {
            get {
                return ResourceManager.GetString("Descuentos_FechaFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Inicial.
        /// </summary>
        internal static string Descuentos_FechaInicial {
            get {
                return ResourceManager.GetString("Descuentos_FechaInicial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo de Producto.
        /// </summary>
        internal static string Descuentos_GrupoProducto {
            get {
                return ResourceManager.GetString("Descuentos_GrupoProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID  Atencion.
        /// </summary>
        internal static string Descuentos_IAtencion {
            get {
                return ResourceManager.GetString("Descuentos_IAtencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Condiciones Cubrimientos.
        /// </summary>
        internal static string Descuentos_IdCondicionesCubrimientos {
            get {
                return ResourceManager.GetString("Descuentos_IdCondicionesCubrimientos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Descuentos.
        /// </summary>
        internal static string Descuentos_IdDescuento {
            get {
                return ResourceManager.GetString("Descuentos_IdDescuento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificador.
        /// </summary>
        internal static string Descuentos_Identificador {
            get {
                return ResourceManager.GetString("Descuentos_Identificador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Descuento.
        /// </summary>
        internal static string Descuentos_ModificarDescuento {
            get {
                return ResourceManager.GetString("Descuentos_ModificarDescuento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha realizado la actualización del descuento.
        /// </summary>
        internal static string Descuentos_MsjActualizacion {
            get {
                return ResourceManager.GetString("Descuentos_MsjActualizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No fue posible realizar la actualización del descuento.
        /// </summary>
        internal static string Descuentos_MsjActualizacionError {
            get {
                return ResourceManager.GetString("Descuentos_MsjActualizacionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha realizado la creación del descuento {0} .
        /// </summary>
        internal static string Descuentos_MsjInsercion {
            get {
                return ResourceManager.GetString("Descuentos_MsjInsercion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan.
        /// </summary>
        internal static string Descuentos_Plan {
            get {
                return ResourceManager.GetString("Descuentos_Plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producto.
        /// </summary>
        internal static string Descuentos_Producto {
            get {
                return ResourceManager.GetString("Descuentos_Producto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Producto.
        /// </summary>
        internal static string Descuentos_TipoProducto {
            get {
                return ResourceManager.GetString("Descuentos_TipoProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Relación.
        /// </summary>
        internal static string Descuentos_TipoRelacion {
            get {
                return ResourceManager.GetString("Descuentos_TipoRelacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descuentos de contratos.
        /// </summary>
        internal static string Descuentos_Titulo {
            get {
                return ResourceManager.GetString("Descuentos_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condiciones Cubrimientos.
        /// </summary>
        internal static string Descuentos_TituloCondicionesCubrimientos {
            get {
                return ResourceManager.GetString("Descuentos_TituloCondicionesCubrimientos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar descuento.
        /// </summary>
        internal static string Descuentos_TituloConsultar {
            get {
                return ResourceManager.GetString("Descuentos_TituloConsultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear descuento.
        /// </summary>
        internal static string Descuentos_TituloCrear {
            get {
                return ResourceManager.GetString("Descuentos_TituloCrear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar descuento.
        /// </summary>
        internal static string Descuentos_TituloModificar {
            get {
                return ResourceManager.GetString("Descuentos_TituloModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor.
        /// </summary>
        internal static string Descuentos_Valor {
            get {
                return ResourceManager.GetString("Descuentos_Valor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Descuentos.
        /// </summary>
        internal static string Descuentos_ValorDescuentos {
            get {
                return ResourceManager.GetString("Descuentos_ValorDescuentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualización.
        /// </summary>
        internal static string Descuentos_Visualizacion {
            get {
                return ResourceManager.GetString("Descuentos_Visualizacion", resourceCulture);
            }
        }
    }
}
