//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Exclusiones {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Exclusiones() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Exclusiones", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusión Activa.
        /// </summary>
        internal static string Exclusiones_Activa {
            get {
                return ResourceManager.GetString("Exclusiones_Activa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salir.
        /// </summary>
        internal static string Exclusiones_BtnSalir {
            get {
                return ResourceManager.GetString("Exclusiones_BtnSalir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salir.
        /// </summary>
        internal static string Exclusiones_BtnSalirToolTip {
            get {
                return ResourceManager.GetString("Exclusiones_BtnSalirToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo de Producto.
        /// </summary>
        internal static string Exclusiones_GrupoProducto {
            get {
                return ResourceManager.GetString("Exclusiones_GrupoProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicar.
        /// </summary>
        internal static string Exclusiones_GrvChkAplicar {
            get {
                return ResourceManager.GetString("Exclusiones_GrvChkAplicar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicar Exclusión.
        /// </summary>
        internal static string Exclusiones_GrvChkAplicarToolTip {
            get {
                return ResourceManager.GetString("Exclusiones_GrvChkAplicarToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Exclusión.
        /// </summary>
        internal static string Exclusiones_IdExclusion {
            get {
                return ResourceManager.GetString("Exclusiones_IdExclusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual ó Contrato.
        /// </summary>
        internal static string Exclusiones_ManualOContrato {
            get {
                return ResourceManager.GetString("Exclusiones_ManualOContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producto.
        /// </summary>
        internal static string Exclusiones_Producto {
            get {
                return ResourceManager.GetString("Exclusiones_Producto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producto Alterno.
        /// </summary>
        internal static string Exclusiones_ProductoAlterno {
            get {
                return ResourceManager.GetString("Exclusiones_ProductoAlterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicio.
        /// </summary>
        internal static string Exclusiones_Servicio {
            get {
                return ResourceManager.GetString("Exclusiones_Servicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Atención.
        /// </summary>
        internal static string Exclusiones_TipoAtencion {
            get {
                return ResourceManager.GetString("Exclusiones_TipoAtencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Producto.
        /// </summary>
        internal static string Exclusiones_TipoProducto {
            get {
                return ResourceManager.GetString("Exclusiones_TipoProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Exclusión.
        /// </summary>
        internal static string Exclusiones_TitConsultar {
            get {
                return ResourceManager.GetString("Exclusiones_TitConsultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Exclusión.
        /// </summary>
        internal static string Exclusiones_TitCrear {
            get {
                return ResourceManager.GetString("Exclusiones_TitCrear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Exclusión.
        /// </summary>
        internal static string Exclusiones_TitModificar {
            get {
                return ResourceManager.GetString("Exclusiones_TitModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definir Exclusiones por Contrato y Manual.
        /// </summary>
        internal static string Exclusiones_Titulo {
            get {
                return ResourceManager.GetString("Exclusiones_Titulo", resourceCulture);
            }
        }
    }
}
