//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalWeb {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalWeb() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.GlobalWeb", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T.
        /// </summary>
        internal static string AnulacionFactura_TipoNota {
            get {
                return ResourceManager.GetString("AnulacionFactura_TipoNota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        internal static string Autenticacion_EstadoActivo {
            get {
                return ResourceManager.GetString("Autenticacion_EstadoActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I.
        /// </summary>
        internal static string Autenticacion_EstadoInactivo {
            get {
                return ResourceManager.GetString("Autenticacion_EstadoInactivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario y/o Contraseña no válidos !!!.
        /// </summary>
        internal static string Autenticacion_MensajeError {
            get {
                return ResourceManager.GetString("Autenticacion_MensajeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Usuario: {0}.
        /// </summary>
        internal static string Autenticacion_NombreCompletoUsuario {
            get {
                return ResourceManager.GetString("Autenticacion_NombreCompletoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BILFA1.
        /// </summary>
        internal static string Autenticacion_RolFacturador {
            get {
                return ResourceManager.GetString("Autenticacion_RolFacturador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario {0} no tiene permisos de acceso al sistema !!!.
        /// </summary>
        internal static string Autenticacion_UsuarioDenegado {
            get {
                return ResourceManager.GetString("Autenticacion_UsuarioDenegado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario {0} esta como Inactivo !!!.
        /// </summary>
        internal static string Autenticacion_UsuarioInactivo {
            get {
                return ResourceManager.GetString("Autenticacion_UsuarioInactivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TipRel.
        /// </summary>
        internal static string CodGenLista_Relacion {
            get {
                return ResourceManager.GetString("CodGenLista_Relacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TipVis.
        /// </summary>
        internal static string CodGenLista_Visualizacion {
            get {
                return ResourceManager.GetString("CodGenLista_Visualizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AC.
        /// </summary>
        internal static string CodigoTipoFacturacion_Actividad {
            get {
                return ResourceManager.GetString("CodigoTipoFacturacion_Actividad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PR.
        /// </summary>
        internal static string CodigoTipoFacturacion_NoClinica {
            get {
                return ResourceManager.GetString("CodigoTipoFacturacion_NoClinica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PA.
        /// </summary>
        internal static string CodigoTipoFacturacion_Paquetes {
            get {
                return ResourceManager.GetString("CodigoTipoFacturacion_Paquetes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RA.
        /// </summary>
        internal static string CodigoTipoFacturacion_Relacion {
            get {
                return ResourceManager.GetString("CodigoTipoFacturacion_Relacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        internal static string ComandoEliminar {
            get {
                return ResourceManager.GetString("ComandoEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facturar.
        /// </summary>
        internal static string ComandoFacturar {
            get {
                return ResourceManager.GetString("ComandoFacturar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprimir.
        /// </summary>
        internal static string ComandoImprimir {
            get {
                return ResourceManager.GetString("ComandoImprimir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo.
        /// </summary>
        internal static string ComandoInsertar {
            get {
                return ResourceManager.GetString("ComandoInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar.
        /// </summary>
        internal static string ComandoModificar {
            get {
                return ResourceManager.GetString("ComandoModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar.
        /// </summary>
        internal static string ComandoSeleccionar {
            get {
                return ResourceManager.GetString("ComandoSeleccionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se creo el concepto de Cobro satisfactoriamente..
        /// </summary>
        internal static string ConceptoCobro_MsjCreacion {
            get {
                return ResourceManager.GetString("ConceptoCobro_MsjCreacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede crear conceptos de cobro para esta vinculación..
        /// </summary>
        internal static string ConceptoCobro_MsjErrorCrear {
            get {
                return ResourceManager.GetString("ConceptoCobro_MsjErrorCrear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El valor del concepto del particular es mayor que el Valor del Deposito..
        /// </summary>
        internal static string ConceptoCobro_MsjValorConcepto {
            get {
                return ResourceManager.GetString("ConceptoCobro_MsjValorConcepto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuracion.
        /// </summary>
        internal static string Configuracion_Modo_Pantalla {
            get {
                return ResourceManager.GetString("Configuracion_Modo_Pantalla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TValComp.
        /// </summary>
        internal static string ContratoComponentes_TipoValor {
            get {
                return ResourceManager.GetString("ContratoComponentes_TipoValor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puede cruzar un valor mayor al deposito.
        /// </summary>
        internal static string Cruzar_Depositos_Mensaje {
            get {
                return ResourceManager.GetString("Cruzar_Depositos_Mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puede cruzar un valor mayor al valor total de la factura.
        /// </summary>
        internal static string Cruzar_Depositos_Valor_Mensaje {
            get {
                return ResourceManager.GetString("Cruzar_Depositos_Valor_Mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puede cruzar el valor de deposito. Se utilizo : {0} en los copagos. El valor disponible es : {1}.
        /// </summary>
        internal static string Depositos_Cruzar_Parcial_Mensaje {
            get {
                return ResourceManager.GetString("Depositos_Cruzar_Parcial_Mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puede cruzar el valor de deposito. El valor completo se utilizo  en los copagos. Total copagos:  {0}.
        /// </summary>
        internal static string Depositos_Cruzar_Total_Mensaje {
            get {
                return ResourceManager.GetString("Depositos_Cruzar_Total_Mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizar.
        /// </summary>
        internal static string Descuentos_Acturalizar_Operacion {
            get {
                return ResourceManager.GetString("Descuentos_Acturalizar_Operacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insertar.
        /// </summary>
        internal static string Descuentos_Insertar_Operacion {
            get {
                return ResourceManager.GetString("Descuentos_Insertar_Operacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensaje.
        /// </summary>
        internal static string Dialogo {
            get {
                return ResourceManager.GetString("Dialogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imgError.
        /// </summary>
        internal static string Dialogo_EstiloError {
            get {
                return ResourceManager.GetString("Dialogo_EstiloError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imgOk.
        /// </summary>
        internal static string Dialogo_EstiloOK {
            get {
                return ResourceManager.GetString("Dialogo_EstiloOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MostrarMensaje(&apos;{0}&apos;,&apos;{1}&apos;);.
        /// </summary>
        internal static string Dialogo_JavaScript {
            get {
                return ResourceManager.GetString("Dialogo_JavaScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class={0}&gt;{1}&lt;/span&gt;.
        /// </summary>
        internal static string Dialogo_Mensaje {
            get {
                return ResourceManager.GetString("Dialogo_Mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facturación Clínica del Country.
        /// </summary>
        internal static string Dialogo_Titulo {
            get {
                return ResourceManager.GetString("Dialogo_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DiasSema.
        /// </summary>
        internal static string DiasDeLaSemana {
            get {
                return ResourceManager.GetString("DiasDeLaSemana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EstDevol.
        /// </summary>
        internal static string EstadoDevolucion {
            get {
                return ResourceManager.GetString("EstadoDevolucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EstVenta.
        /// </summary>
        internal static string EstadoVenta {
            get {
                return ResourceManager.GetString("EstadoVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MensajeERROR.
        /// </summary>
        internal static string Estilo_MensajeERROR {
            get {
                return ResourceManager.GetString("Estilo_MensajeERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MensajeOK.
        /// </summary>
        internal static string Estilo_MensajeOK {
            get {
                return ResourceManager.GetString("Estilo_MensajeOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hubo un problema al actualizar el estado de bloqueo de la atención..
        /// </summary>
        internal static string FacturacionActividades_ErrorAtencionBloqueada {
            get {
                return ResourceManager.GetString("FacturacionActividades_ErrorAtencionBloqueada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facturacion.
        /// </summary>
        internal static string Facturacion_Modo_Pantalla {
            get {
                return ResourceManager.GetString("Facturacion_Modo_Pantalla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D.
        /// </summary>
        internal static string Formato_Decimal {
            get {
                return ResourceManager.GetString("Formato_Decimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0.#}.
        /// </summary>
        internal static string Formato_DecimalString {
            get {
                return ResourceManager.GetString("Formato_DecimalString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceso Denegado..
        /// </summary>
        internal static string General_AccesoDenegado {
            get {
                return ResourceManager.GetString("General_AccesoDenegado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizar Vinculaciones.
        /// </summary>
        internal static string General_ActualizarVinculaciones {
            get {
                return ResourceManager.GetString("General_ActualizarVinculaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los productos asociados a la atención no cumplen las condiciones para incluirlos en la facturación..
        /// </summary>
        internal static string General_Atencion_SinProductos {
            get {
                return ResourceManager.GetString("General_Atencion_SinProductos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar.
        /// </summary>
        internal static string General_BotonAdicionar {
            get {
                return ResourceManager.GetString("General_BotonAdicionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar responsable del particular.
        /// </summary>
        internal static string General_BotonBuscaResponsableParticular {
            get {
                return ResourceManager.GetString("General_BotonBuscaResponsableParticular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar.
        /// </summary>
        internal static string General_BotonCerrar {
            get {
                return ResourceManager.GetString("General_BotonCerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condiciones de Cubrimiento.
        /// </summary>
        internal static string General_BotonCondicionCubrimiento {
            get {
                return ResourceManager.GetString("General_BotonCondicionCubrimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condiciones de Facturación.
        /// </summary>
        internal static string General_BotonCondicionFacturacion {
            get {
                return ResourceManager.GetString("General_BotonCondicionFacturacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condiciones de Tarifa.
        /// </summary>
        internal static string General_BotonCondicionTarifa {
            get {
                return ResourceManager.GetString("General_BotonCondicionTarifa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar.
        /// </summary>
        internal static string General_BotonConsultar {
            get {
                return ResourceManager.GetString("General_BotonConsultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definir Cortes de Facturación.
        /// </summary>
        internal static string General_BotonCortesFacturacion {
            get {
                return ResourceManager.GetString("General_BotonCortesFacturacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definir Condiciones.
        /// </summary>
        internal static string General_BotonDefinirCondiciones {
            get {
                return ResourceManager.GetString("General_BotonDefinirCondiciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definir Cubrimientos.
        /// </summary>
        internal static string General_BotonDefinirCubrimiento {
            get {
                return ResourceManager.GetString("General_BotonDefinirCubrimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definir Exclusiones.
        /// </summary>
        internal static string General_BotonDefinirExclusiones {
            get {
                return ResourceManager.GetString("General_BotonDefinirExclusiones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descuentos.
        /// </summary>
        internal static string General_BotonDescuentos {
            get {
                return ResourceManager.GetString("General_BotonDescuentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        internal static string General_BotonEditar {
            get {
                return ResourceManager.GetString("General_BotonEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GENERAR ESTADO DE CUENTA.
        /// </summary>
        internal static string General_BotonEstadoCuenta {
            get {
                return ResourceManager.GetString("General_BotonEstadoCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado de Cuenta Detallado.
        /// </summary>
        internal static string General_BotonEstadoCuentaDetallado {
            get {
                return ResourceManager.GetString("General_BotonEstadoCuentaDetallado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GENERAR REPORTE VENTA.
        /// </summary>
        internal static string General_BotonGenerarReporte {
            get {
                return ResourceManager.GetString("General_BotonGenerarReporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        internal static string General_BotonGuardar {
            get {
                return ResourceManager.GetString("General_BotonGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar.
        /// </summary>
        internal static string General_BotonModificar {
            get {
                return ResourceManager.GetString("General_BotonModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo.
        /// </summary>
        internal static string General_BotonNuevo {
            get {
                return ResourceManager.GetString("General_BotonNuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procesar.
        /// </summary>
        internal static string General_BotonProcesar {
            get {
                return ResourceManager.GetString("General_BotonProcesar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regresar.
        /// </summary>
        internal static string General_BotonRegresar {
            get {
                return ResourceManager.GetString("General_BotonRegresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relacionar ventas a la atención actual.
        /// </summary>
        internal static string General_BotonRelacionarVentas {
            get {
                return ResourceManager.GetString("General_BotonRelacionarVentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salir.
        /// </summary>
        internal static string General_BotonSalir {
            get {
                return ResourceManager.GetString("General_BotonSalir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vincular Entidad.
        /// </summary>
        internal static string General_BotonVincularEntidad {
            get {
                return ResourceManager.GetString("General_BotonVincularEntidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        internal static string General_Buscar {
            get {
                return ResourceManager.GetString("General_Buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BIL.
        /// </summary>
        internal static string General_CodigoModulFact {
            get {
                return ResourceManager.GetString("General_CodigoModulFact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione Todos.
        /// </summary>
        internal static string General_ComboItemSeleccionTodos {
            get {
                return ResourceManager.GetString("General_ComboItemSeleccionTodos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECCIONE....
        /// </summary>
        internal static string General_ComboItemTexto {
            get {
                return ResourceManager.GetString("General_ComboItemTexto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string General_ComboItemValor {
            get {
                return ResourceManager.GetString("General_ComboItemValor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodEsor.
        /// </summary>
        internal static string General_ComboPropiedadCodEsor {
            get {
                return ResourceManager.GetString("General_ComboPropiedadCodEsor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        internal static string General_ComboPropiedadTexto {
            get {
                return ResourceManager.GetString("General_ComboPropiedadTexto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripcion.
        /// </summary>
        internal static string General_ComboPropiedadTexto_TipoFacrtura {
            get {
                return ResourceManager.GetString("General_ComboPropiedadTexto_TipoFacrtura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string General_ComboPropiedadValor {
            get {
                return ResourceManager.GetString("General_ComboPropiedadValor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdPlan.
        /// </summary>
        internal static string General_ComboPropiedadValor_Plan {
            get {
                return ResourceManager.GetString("General_ComboPropiedadValor_Plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codigo.
        /// </summary>
        internal static string General_ComboPropiedadValor_TipoFacrtura {
            get {
                return ResourceManager.GetString("General_ComboPropiedadValor_TipoFacrtura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfigurarPermisos({0});.
        /// </summary>
        internal static string General_ConfigurarPermisos {
            get {
                return ResourceManager.GetString("General_ConfigurarPermisos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar.
        /// </summary>
        internal static string General_Confirmar {
            get {
                return ResourceManager.GetString("General_Confirmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No  existe Información  para el criterio de Busqueda seleccionado.
        /// </summary>
        internal static string General_CriterioBusqueda {
            get {
                return ResourceManager.GetString("General_CriterioBusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar ventas para poder generar el estado de cuenta..
        /// </summary>
        internal static string General_DebeSeleccionarVentas {
            get {
                return ResourceManager.GetString("General_DebeSeleccionarVentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        internal static string General_EstadoActivo {
            get {
                return ResourceManager.GetString("General_EstadoActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^\d{1,2}(\.\d{1,2})?$.
        /// </summary>
        internal static string General_ExpresionDecimal_2E_2D {
            get {
                return ResourceManager.GetString("General_ExpresionDecimal_2E_2D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^\d{1,3}(\.\d{1,2})?$.
        /// </summary>
        internal static string General_ExpresionDecimal_3E_2D {
            get {
                return ResourceManager.GetString("General_ExpresionDecimal_3E_2D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^([\w\.\-]+)@([\w\-]+)((\.(\w){2,3})+)$.
        /// </summary>
        internal static string General_ExpresionEmail {
            get {
                return ResourceManager.GetString("General_ExpresionEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo email se encuentra mal diligenciado.
        /// </summary>
        internal static string General_ExpresionEmailMensaje {
            get {
                return ResourceManager.GetString("General_ExpresionEmailMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^(0[1-9]|[12][0-9]|3[01])[-/.](0[1-9]|1[012])[-/.](19|20)\d\d$.
        /// </summary>
        internal static string General_ExpresionRegularFecha {
            get {
                return ResourceManager.GetString("General_ExpresionRegularFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \d{9}.
        /// </summary>
        internal static string General_ExpresionRegularNIT {
            get {
                return ResourceManager.GetString("General_ExpresionRegularNIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El número de NIT debe tener nueve caracteres.
        /// </summary>
        internal static string General_ExpresionRegularNITMensaje {
            get {
                return ResourceManager.GetString("General_ExpresionRegularNITMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El rango de fechas seleccionadas no corresponde a fechas dentro de las ventas de la atención o se encuentran cargadas dentro de los rangos de fechas de la selección en la parte inferior..
        /// </summary>
        internal static string General_FechaGrillaCortesFacturacion {
            get {
                return ResourceManager.GetString("General_FechaGrillaCortesFacturacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha es inválida.
        /// </summary>
        internal static string General_FechaInvalida {
            get {
                return ResourceManager.GetString("General_FechaInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01/01/1753.
        /// </summary>
        internal static string General_FechaMinimaSQL {
            get {
                return ResourceManager.GetString("General_FechaMinimaSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd/MM/yyyy.
        /// </summary>
        internal static string General_FormatoFecha {
            get {
                return ResourceManager.GetString("General_FormatoFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __/__/____.
        /// </summary>
        internal static string General_FormatoFechaVacio {
            get {
                return ResourceManager.GetString("General_FormatoFechaVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato inválido.
        /// </summary>
        internal static string General_FormatoInvalido {
            get {
                return ResourceManager.GetString("General_FormatoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99/99/9999.
        /// </summary>
        internal static string General_FormatoMascaraFecha {
            get {
                return ResourceManager.GetString("General_FormatoMascaraFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:C0}.
        /// </summary>
        internal static string General_FormatStringNumero {
            get {
                return ResourceManager.GetString("General_FormatStringNumero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay coincidencias para los parámetros ingresados..
        /// </summary>
        internal static string General_GrillaSinDatos {
            get {
                return ResourceManager.GetString("General_GrillaSinDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La información  fue almacenada de manera exitosa con Id  .
        /// </summary>
        internal static string General_GuardaCondicionesTarifa {
            get {
                return ResourceManager.GetString("General_GuardaCondicionesTarifa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La información  fue almacenada de manera exitosa con Id  .
        /// </summary>
        internal static string General_GuardarDescuentos {
            get {
                return ResourceManager.GetString("General_GuardarDescuentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdTipoProducto.
        /// </summary>
        internal static string General_IdTipoProducto {
            get {
                return ResourceManager.GetString("General_IdTipoProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        internal static string General_IndHabilitado {
            get {
                return ResourceManager.GetString("General_IndHabilitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese una Fecha.
        /// </summary>
        internal static string General_IngreseFecha {
            get {
                return ResourceManager.GetString("General_IngreseFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conceptos.
        /// </summary>
        internal static string General_LabelConceptos {
            get {
                return ResourceManager.GetString("General_LabelConceptos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado Cuenta.
        /// </summary>
        internal static string General_LabelEstadoCuenta {
            get {
                return ResourceManager.GetString("General_LabelEstadoCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Facturable.
        /// </summary>
        internal static string General_LabelNoFacturable {
            get {
                return ResourceManager.GetString("General_LabelNoFacturable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 000.00.
        /// </summary>
        internal static string General_MascaraPorcentajeCero {
            get {
                return ResourceManager.GetString("General_MascaraPorcentajeCero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de movimiento de no cobrables.
        /// </summary>
        internal static string General_Mensaje1 {
            get {
                return ResourceManager.GetString("General_Mensaje1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO FACTURABLES.
        /// </summary>
        internal static string General_Mensaje2 {
            get {
                return ResourceManager.GetString("General_Mensaje2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha inicial no puede ser mayor que la fecha final..
        /// </summary>
        internal static string General_MensajeErrorFecha1 {
            get {
                return ResourceManager.GetString("General_MensajeErrorFecha1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha final no puede ser superior a la fecha actual..
        /// </summary>
        internal static string General_MensajeErrorFecha2 {
            get {
                return ResourceManager.GetString("General_MensajeErrorFecha2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El formato de fecha debe estar en dd/MM/yyyy..
        /// </summary>
        internal static string General_MensajeErrorFecha3 {
            get {
                return ResourceManager.GetString("General_MensajeErrorFecha3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha final no puede ser menor que la fecha inicial..
        /// </summary>
        internal static string General_MensajeErrorFecha4 {
            get {
                return ResourceManager.GetString("General_MensajeErrorFecha4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha ingresada no puede ser superior a la fecha actual..
        /// </summary>
        internal static string General_MensajeErrorFechaSuperior {
            get {
                return ResourceManager.GetString("General_MensajeErrorFechaSuperior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        internal static string General_Mensaje_Buscar {
            get {
                return ResourceManager.GetString("General_Mensaje_Buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe estar autenticado y tener permisos sobre la pagina que intento ingresar..
        /// </summary>
        internal static string General_Msj_IngresoNoAutorizado {
            get {
                return ResourceManager.GetString("General_Msj_IngresoNoAutorizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existen permisos asociados al usuario {0}..
        /// </summary>
        internal static string General_NoExistenPermisos {
            get {
                return ResourceManager.GetString("General_NoExistenPermisos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        internal static string General_Nombre {
            get {
                return ResourceManager.GetString("General_Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NombreMaestroDetalle.
        /// </summary>
        internal static string General_NombreMaestroDetalle {
            get {
                return ResourceManager.GetString("General_NombreMaestroDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El objeto es nulo..
        /// </summary>
        internal static string General_ObjetoNulo {
            get {
                return ResourceManager.GetString("General_ObjetoNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultado de la Búsqueda.
        /// </summary>
        internal static string General_ResultadoBusqueda {
            get {
                return ResourceManager.GetString("General_ResultadoBusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERMISOPAGINAUSUARIO.
        /// </summary>
        internal static string General_Session_PERMISOPAGINAUSUARIO {
            get {
                return ResourceManager.GetString("General_Session_PERMISOPAGINAUSUARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe Adicionar Productos para Guardar la Venta.
        /// </summary>
        internal static string General_SinProductos {
            get {
                return ResourceManager.GetString("General_SinProductos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay ventas pendientes.
        /// </summary>
        internal static string General_SinVentas {
            get {
                return ResourceManager.GetString("General_SinVentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenido(a) - SISTEMA DE FACTURACIÓN.
        /// </summary>
        internal static string General_Text_Bienvenida {
            get {
                return ResourceManager.GetString("General_Text_Bienvenida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        internal static string General_TipoCondicionCubrimiento {
            get {
                return ResourceManager.GetString("General_TipoCondicionCubrimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Registros: {0}.
        /// </summary>
        internal static string General_TotalRegistros {
            get {
                return ResourceManager.GetString("General_TotalRegistros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario {0}, no se encuentra autorizado..
        /// </summary>
        internal static string General_UsuarioNoAurotizado {
            get {
                return ResourceManager.GetString("General_UsuarioNoAurotizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^(0|[1-9][0-9]{0,9})$.
        /// </summary>
        internal static string General_ValidacionNumero {
            get {
                return ResourceManager.GetString("General_ValidacionNumero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se permite valor Cero en Ajuste de Tarifa..
        /// </summary>
        internal static string General_ValorCampoAjusteTarifa {
            get {
                return ResourceManager.GetString("General_ValorCampoAjusteTarifa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo es obligatorio..
        /// </summary>
        internal static string General_ValorCampoObligatorio {
            get {
                return ResourceManager.GetString("General_ValorCampoObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El porcentaje asignado es incorrecto..
        /// </summary>
        internal static string General_ValorCampoPorcentaje {
            get {
                return ResourceManager.GetString("General_ValorCampoPorcentaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string General_ValorCCPorcentaje {
            get {
                return ResourceManager.GetString("General_ValorCCPorcentaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string General_ValorCero {
            get {
                return ResourceManager.GetString("General_ValorCero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01/01/1900.
        /// </summary>
        internal static string General_ValorDefectoFecha {
            get {
                return ResourceManager.GetString("General_ValorDefectoFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generar consulta..
        /// </summary>
        internal static string General_ValorGenerarConsulta {
            get {
                return ResourceManager.GetString("General_ValorGenerarConsulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor.
        /// </summary>
        internal static string General_ValorMaestroDetalle {
            get {
                return ResourceManager.GetString("General_ValorMaestroDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El valor debe ser mayor a 0.
        /// </summary>
        internal static string General_ValorMayorCero {
            get {
                return ResourceManager.GetString("General_ValorMayorCero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        internal static string General_ValorN {
            get {
                return ResourceManager.GetString("General_ValorN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NA.
        /// </summary>
        internal static string General_ValorNA {
            get {
                return ResourceManager.GetString("General_ValorNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string General_ValorNegativo {
            get {
                return ResourceManager.GetString("General_ValorNegativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string General_ValorUno {
            get {
                return ResourceManager.GetString("General_ValorUno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TipAprox.
        /// </summary>
        internal static string Global_CodGrupoTipoCriterio {
            get {
                return ResourceManager.GetString("Global_CodGrupoTipoCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vincular Entidad.
        /// </summary>
        internal static string Global_VincularEntidad {
            get {
                return ResourceManager.GetString("Global_VincularEntidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ** COPIA **.
        /// </summary>
        internal static string ImpresionCopiaFactura {
            get {
                return ResourceManager.GetString("ImpresionCopiaFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar una entidad en la grilla de anterior..
        /// </summary>
        internal static string Mensaje_Descuentos_Entidades {
            get {
                return ResourceManager.GetString("Mensaje_Descuentos_Entidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MetPagos.
        /// </summary>
        internal static string MetodosPago {
            get {
                return ResourceManager.GetString("MetodosPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenida.aspx.
        /// </summary>
        internal static string PaginaDefault_Bienvenida {
            get {
                return ResourceManager.GetString("PaginaDefault_Bienvenida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.aspx.
        /// </summary>
        internal static string PaginaDefault_Login {
            get {
                return ResourceManager.GetString("PaginaDefault_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Página Anterior.
        /// </summary>
        internal static string Paginador_Anterior {
            get {
                return ResourceManager.GetString("Paginador_Anterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Página:  {0} de {1}.
        /// </summary>
        internal static string Paginador_ControlPaginas {
            get {
                return ResourceManager.GetString("Paginador_ControlPaginas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primera Página.
        /// </summary>
        internal static string Paginador_Primera {
            get {
                return ResourceManager.GetString("Paginador_Primera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Página Siguiente.
        /// </summary>
        internal static string Paginador_Siguiente {
            get {
                return ResourceManager.GetString("Paginador_Siguiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Registros: {0}.
        /// </summary>
        internal static string Paginador_TotalRegistros {
            get {
                return ResourceManager.GetString("Paginador_TotalRegistros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Última Página.
        /// </summary>
        internal static string Paginador_Ultima {
            get {
                return ResourceManager.GetString("Paginador_Ultima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        internal static string PaginaMaestra_Texto_Inicio {
            get {
                return ResourceManager.GetString("PaginaMaestra_Texto_Inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salir.
        /// </summary>
        internal static string PaginaMaestra_Texto_Salir {
            get {
                return ResourceManager.GetString("PaginaMaestra_Texto_Salir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReporteProductosNoFacturable.aspx.
        /// </summary>
        internal static string ReporteFactura_NoFacturables {
            get {
                return ResourceManager.GetString("ReporteFactura_NoFacturables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AtencionCliente.
        /// </summary>
        internal static string Session_AtencionActiva {
            get {
                return ResourceManager.GetString("Session_AtencionActiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CondicionContrato.
        /// </summary>
        internal static string Session_CondicionContrato {
            get {
                return ResourceManager.GetString("Session_CondicionContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContratoEstancia.
        /// </summary>
        internal static string Session_ContratoEstancia {
            get {
                return ResourceManager.GetString("Session_ContratoEstancia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EstadoCuentaEncabezado.
        /// </summary>
        internal static string Session_EstadoCuentaEncabezado {
            get {
                return ResourceManager.GetString("Session_EstadoCuentaEncabezado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImprimirFactura.
        /// </summary>
        internal static string Session_EstadoCuentaFacturaImpresa {
            get {
                return ResourceManager.GetString("Session_EstadoCuentaFacturaImpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TipoEstadoCuenta.
        /// </summary>
        internal static string Session_EstadoCuentaTipo {
            get {
                return ResourceManager.GetString("Session_EstadoCuentaTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VentaNoQX.
        /// </summary>
        internal static string Session_EstadoCuentaVentaNoQX {
            get {
                return ResourceManager.GetString("Session_EstadoCuentaVentaNoQX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExclusionesManual.
        /// </summary>
        internal static string Session_ExclusionesManual {
            get {
                return ResourceManager.GetString("Session_ExclusionesManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FactoresNoQX.
        /// </summary>
        internal static string Session_FactoresNoQX {
            get {
                return ResourceManager.GetString("Session_FactoresNoQX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FacturaNoClinicaReporte.
        /// </summary>
        internal static string Session_FacturaNoClinicaReporte {
            get {
                return ResourceManager.GetString("Session_FacturaNoClinicaReporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seccion.
        /// </summary>
        internal static string Session_ListadoSecciones {
            get {
                return ResourceManager.GetString("Session_ListadoSecciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DetalleVenta.
        /// </summary>
        internal static string Session_Productos {
            get {
                return ResourceManager.GetString("Session_Productos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RolesUsuario.
        /// </summary>
        internal static string Session_RolesUsuario {
            get {
                return ResourceManager.GetString("Session_RolesUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TipoFacturacion.
        /// </summary>
        internal static string Session_TipoFacturacion {
            get {
                return ResourceManager.GetString("Session_TipoFacturacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VigenciaTarifaEntidad.
        /// </summary>
        internal static string Session_VigenciaTarifaEntidad {
            get {
                return ResourceManager.GetString("Session_VigenciaTarifaEntidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vinculacion.
        /// </summary>
        internal static string Session_Vinculacion {
            get {
                return ResourceManager.GetString("Session_Vinculacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string TipoProducto_IdProcedmientoQx {
            get {
                return ResourceManager.GetString("TipoProducto_IdProcedmientoQx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TiposTar.
        /// </summary>
        internal static string TiposTarifa {
            get {
                return ResourceManager.GetString("TiposTarifa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TiposVal.
        /// </summary>
        internal static string TiposValor {
            get {
                return ResourceManager.GetString("TiposValor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UsuarioNombreCompleto.
        /// </summary>
        internal static string Usuario_NombreCompleto {
            get {
                return ResourceManager.GetString("Usuario_NombreCompleto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Módulo Facturación Vr. 1.0.22.0.
        /// </summary>
        internal static string Version_AplicacionFacturacion {
            get {
                return ResourceManager.GetString("Version_AplicacionFacturacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © Copyright 2013 – Todos los derechos reservados Clínica del Country | Carrera 16 No.82-57 | Conmutador 530-0470 / 530-1270 | Bogotá - Colombia.
        /// </summary>
        internal static string Version_Copyright {
            get {
                return ResourceManager.GetString("Version_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.9.1.
        /// </summary>
        internal static string Version_JQuery {
            get {
                return ResourceManager.GetString("Version_JQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar Cambios.
        /// </summary>
        internal static string Vinculacion_GuardarCambios {
            get {
                return ResourceManager.GetString("Vinculacion_GuardarCambios", resourceCulture);
            }
        }
    }
}
