//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Reportes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Reportes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Reportes", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~\ReportesFacturacion\NoFacturable.rdlc.
        /// </summary>
        internal static string FacActividad_RptNoFacturable {
            get {
                return ResourceManager.GetString("FacActividad_RptNoFacturable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha generado la factura No {0}, el proceso fue satisfactorio.
        /// </summary>
        internal static string FacturaAlmacenada_Mensaje {
            get {
                return ResourceManager.GetString("FacturaAlmacenada_Mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle.
        /// </summary>
        internal static string FacturacionAgrupada_DataSet_Detalle {
            get {
                return ResourceManager.GetString("FacturacionAgrupada_DataSet_Detalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encabezado.
        /// </summary>
        internal static string FacturacionAgrupada_DataSet_Encabezado {
            get {
                return ResourceManager.GetString("FacturacionAgrupada_DataSet_Encabezado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle.
        /// </summary>
        internal static string FacturacionDetallada_DataSet_Detalle {
            get {
                return ResourceManager.GetString("FacturacionDetallada_DataSet_Detalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encabezado.
        /// </summary>
        internal static string FacturacionDetallada_DataSet_Encabezado {
            get {
                return ResourceManager.GetString("FacturacionDetallada_DataSet_Encabezado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoFacturable.
        /// </summary>
        internal static string FacturacionDetallada_DataSet_NoFacturable {
            get {
                return ResourceManager.GetString("FacturacionDetallada_DataSet_NoFacturable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado de Cuenta.
        /// </summary>
        internal static string FacturacionEstadoCuenta {
            get {
                return ResourceManager.GetString("FacturacionEstadoCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factura.
        /// </summary>
        internal static string FacturacionFactura {
            get {
                return ResourceManager.GetString("FacturacionFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FacturaNoClinicaReporte.
        /// </summary>
        internal static string FacturacionNoClinica_DataSet_Reporte {
            get {
                return ResourceManager.GetString("FacturacionNoClinica_DataSet_Reporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resumen.
        /// </summary>
        internal static string FacturacionResumen {
            get {
                return ResourceManager.GetString("FacturacionResumen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle.
        /// </summary>
        internal static string FacturacionResumen_DataSet_Detalle {
            get {
                return ResourceManager.GetString("FacturacionResumen_DataSet_Detalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encabezado.
        /// </summary>
        internal static string FacturacionResumen_DataSet_Encabezado {
            get {
                return ResourceManager.GetString("FacturacionResumen_DataSet_Encabezado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado de Cuenta.
        /// </summary>
        internal static string Facturacion_NumeroFactura {
            get {
                return ResourceManager.GetString("Facturacion_NumeroFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSAHI.
        /// </summary>
        internal static string Facturacion_Usuario {
            get {
                return ResourceManager.GetString("Facturacion_Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReporteVenta.aspx.
        /// </summary>
        internal static string Reporte_Venta {
            get {
                return ResourceManager.GetString("Reporte_Venta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle.
        /// </summary>
        internal static string Venta_DataSet_Detalle {
            get {
                return ResourceManager.GetString("Venta_DataSet_Detalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encabezado.
        /// </summary>
        internal static string Venta_DataSet_Encabezado {
            get {
                return ResourceManager.GetString("Venta_DataSet_Encabezado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~\ReportesFacturacion\Ventas.rdlc.
        /// </summary>
        internal static string Venta_Reporte {
            get {
                return ResourceManager.GetString("Venta_Reporte", resourceCulture);
            }
        }
    }
}
