//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VincularEntidad {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VincularEntidad() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.VincularEntidad", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se han actualizado las vinculaciones para la atención {0}.
        /// </summary>
        internal static string VinculaEntidad_MsjActualizacion {
            get {
                return ResourceManager.GetString("VinculaEntidad_MsjActualizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        internal static string VincularEntidad_Activo {
            get {
                return ResourceManager.GetString("VincularEntidad_Activo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizar Entidad Vinculada.
        /// </summary>
        internal static string VincularEntidad_Actualizar {
            get {
                return ResourceManager.GetString("VincularEntidad_Actualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrato.
        /// </summary>
        internal static string VincularEntidad_Contrato {
            get {
                return ResourceManager.GetString("VincularEntidad_Contrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrato-Plan.
        /// </summary>
        internal static string VincularEntidad_ContratoPlan {
            get {
                return ResourceManager.GetString("VincularEntidad_ContratoPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entidad.
        /// </summary>
        internal static string VincularEntidad_Entidad {
            get {
                return ResourceManager.GetString("VincularEntidad_Entidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monto Ejecutado.
        /// </summary>
        internal static string VincularEntidad_Montoejecutado {
            get {
                return ResourceManager.GetString("VincularEntidad_Montoejecutado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede actualizar las vinculaciones. Se debe verificar Estado y/o Orden..
        /// </summary>
        internal static string VincularEntidad_MsjError {
            get {
                return ResourceManager.GetString("VincularEntidad_MsjError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nivel.
        /// </summary>
        internal static string VincularEntidad_Nivel {
            get {
                return ResourceManager.GetString("VincularEntidad_Nivel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero de Afiliación.
        /// </summary>
        internal static string VincularEntidad_NumeroAfiliacion {
            get {
                return ResourceManager.GetString("VincularEntidad_NumeroAfiliacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orden.
        /// </summary>
        internal static string VincularEntidad_Orden {
            get {
                return ResourceManager.GetString("VincularEntidad_Orden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan.
        /// </summary>
        internal static string VincularEntidad_Plan {
            get {
                return ResourceManager.GetString("VincularEntidad_Plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Afiliación.
        /// </summary>
        internal static string VincularEntidad_TipoAfiliacion {
            get {
                return ResourceManager.GetString("VincularEntidad_TipoAfiliacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vincular Entidad.
        /// </summary>
        internal static string VincularEntidad_Titulo {
            get {
                return ResourceManager.GetString("VincularEntidad_Titulo", resourceCulture);
            }
        }
    }
}
